### ISSUE TITLE
precinct-scanner: handle scanned ballots when setting precinct

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1009]
Changing the precinct that the precinct-scanner is configured for doesn't reset the ballot data, so you can scan ballots for precinct-1 and then configure the scanner for precinct-2 and there are still precinct-1 ballots in the data.

**Comment by eventualbuddha** [comment]
What should this do? Should we require the polls be closed when changing the precinct? That the ballot data be zeroed out?

**Comment by benadida** [comment]
I believe this should delete scanned ballot data but with a warning first.

cc @mcchilders thoughts?

**Comment by mcchilders** [comment]
What is the reasoning behind this question, I think I'm missing context? Here are a few scenarios where you'd want the same precinct scanner to have diff configs during the same election:

- a precinct scanner config'd to "all precincts" for early voting (at the office) that is then reused as e-day equipment, config'd to a single voting location's precinct(s) 
- e-day equipment, config'd to a single voting location's precinct(s), that is then repurposed for scanning absentee ballots back at the office (some jurisdictions do this because it saves them the cost of buying an expensive central scanner, and they just have a bunch of people feeding ballots through one-by-one at the office)
- an eday scanner at a multi-precinct voting location misconfigured during e-day setup, which only gets noticed partway through the day when the first person from the missing precinct comes in to vote and their ballot won't scan. 

Deleting ballot data is v dicey, and there are good reasons to never do it until the election is fully over, so I would lean towards retaining all ballot data, even when you switch the config on a machine, and then having checks in Election Manager that flag when you're uploading entirely/partially duplicate CVRs within a CVR file (e.g. Scenario 2 above, when you've exported CVRs at the end of e-day and loaded those, but then also exported a cumulative CVR file again after scanning absentee ballots that has both).
