### ISSUE TITLE
"Printer Not Connected" problem still happening on VxMark

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1303]
## Background

The BMD in print mode (either "VxPrint" or "VxMark + VxPrint", though the latter is really the one that matters right now) requires a printer, and without a printer plugged in and turned on, it displays "printer not connected" and refuses to do anything voter or poll-worker related. The admin screen remains functional so a BMD can be configured even if it's not plugged into a printer.

## Problem

In the past, we've seen occasionally the BMD believe that there is no printer connected when in fact there is. The only mitigation is to unplug and replug the printer USB cable. We thought we'd fixed it before, but it's been happening again in the most recent election.

Likely steps to repro: plug in printer *before* turning on the BMD, then turn on BMD.

Another possibility: when the printer goes to sleep after a while.

**Comment by adghayes** [comment]
I was able to reproduce the "Printer Not Connected" issue by:

1. Setting up VxMark
2. Waiting for 15+ minutes

I don't know exactly when the disconnection happened. When I looked, the printer itself was in sleep mode. When I woke the printer from sleep mode, the connection issue was _not_ fixed. I had to disconnect and reconnect the cable to fix. 

I don't think the issue is triggered simply by the printer going into sleep mode. Because my printer goes into sleep mode after just one minute, but the disconnection happens well after that. And waking from sleep mode didn't fix the issue. 

I am _not_ able to reproduce the issue by setting up VxMark in any particular way. Specifically, all 6 permutations of the events - connecting the cord, powering on VxMark, powering on printer - result in a proper connection. It seems like our issue occurs only after the printer has been connected for a while.

**Comment by mattroe** [comment]
Some anecdotal experience from last week:
- When I left the BMD in a non-activated state, the printer not detected would eventually come up. This consistently occurred but I couldn't identify what the exact circumstance was as Drew referred to above.
- When I left the BMD in a activated state, I never saw the printer not detected (though it may have still been an issue) and instead the only ever saw the "clearing vote" screen state (which is a different issue where the clearing vote screen doesn't clear...)

**Comment by carolinemodic** [comment]
Filed: https://github.com/votingworks/vxsuite/issues/1385 for a longer term followup investigation
