### ISSUE TITLE
Print all L&A necessities in one go

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1305]
Notes on what she would like from Ginny: https://docs.google.com/document/d/1M7n9fR7VE-qmcEqpW_lFVW3BCFZBwkbhppv9Q2_qJ2Y/edit
* test ballots
* some blank ballots
* expected tally

Useful point of contacts: 
User need and the problem we're trying to solve - Ginny 
Consult on design / user flow - Beau 
Engineering help on working in VxAdmin - Caroline

**Comment by mcchilders** [comment]
Note that @ginvdr is leading the rethink on this, so should probably hold on this until that is done.

**Comment by beausmith** [comment]
# Proposal

Break "Tally" tab into three tabs:
- L&A
- CVRs
- Tallies

## L&A tab

Because these packages could be very large, we need to determine if there should be one button to print everything, or if we should break it down further to allow printing any part individually. A middle ground would be the ability to print 1 package per precinct with some indication of what has been printed thus far. The number of pages in a package should be noted such that it's clear how much paper will be needed and how much time it'll take.

To assist someone through the process of printing the documents for L&A: the page could be rendered as a checklist — where items are checked off once printed — or have a "last printed" timestamp listed next to each print button.

The page should clarify that "The following L&A materials are for the purpose of testing tabulation on VxScan and VxCentralScan. Ballot marking device testing should be done separately on VxMark."

### Page Content

- List of buttons to print an individual "Precinct Test Deck Package" with number of pages noted:
    - add Expected Precinct Tally Report 
    - current VxMark test deck
    - current HMPB test deck
    - pre-marked overvoted HMPB
    - blank HMPB
    - blank HMPB to be manually filled out which replaces a pre-printed HMPB that will be marked as spoiled.
- Button for printing the expected full election tally results for the jurisdiction.
- Button to print all the above materials
- The pre-election "Unofficial Full Election Tally Report" or "Zero Report" can be printed from the [Tallies page](#)

## CVRs tab

The current content from the top of "tally" page will be moved to create a new page for managing CVRs and other results. 

Content can be grouped by topic: CVRs, External Results (currently only used for SEMS results), Manually Entered Results.

### Page Content

#### CVRs
- Table of "Imported CVR Files"
- Button "Import CVR Files"
- Button "Remove CVR Files…"

#### External Results
Button "Import External Results File"

or 

List: External Results File.
Button "Remove External Results File…"

#### Manually Entered Results
Button "Add Manually Entered Results"

or 

Display: "Manually Entered Results File."
Button "Remove Manually Entered Results…"

## Tallies tab

This page can now be simply used for printing reports. It remains much the same as it is now, other than the "View Unofficial Full Election Tally Report" gets moved to the top of the screen. The button "Mark Tally Results as Official…" is moved to the page for viewing/printing the full election tally report.

### Page Content

Button "View Unofficial Full Election Tally Report"

#### Ballot Counts by Precinct
- table of precincts and reports

#### Ballot Counts by Voting Method
- table of precincts and reports

#### Ballot Counts by Party
- table of precincts and reports

#### Ballot Counts by Scanner
- table of precincts and reports

---- 

End of proposal

**Comment by arsalansufi** [comment]
Captured the contents of this ticket in the product roadmap ticket: https://github.com/votingworks/vxsuite-roadmap/issues/10#issuecomment-1098282821

Closing this ticket out accordingly, as I'll be opening smaller, more granular tickets under the product roadmap ticket
