### ISSUE TITLE
kiosk-browser possibly crashing on Ubuntu20/Debian

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1377]

**Comment by carolinemodic** [comment]
Initial investigation notes: https://votingworks.slack.com/archives/CEL6D3GAD/p1643673731433799 
Unassigning from myself as we are rolling back to ubuntu 18 for m13a

**Comment by carolinemodic** [comment]
I have seen this sometimes just ctrl+c-ing out of kiosk-browser but I'm not completely sure if thats the same error. The best way to repro involves a few minor changes to the code: 

1. Change this config variable from 5 minutes to something small like 10 seconds: https://github.com/votingworks/vxsuite/blob/main/frontends/bmd/src/config/globals.ts#L21 
2. pnpm start to run bmd
3. run the smartcard service
4. modify this script: https://github.com/votingworks/vxsuite-complete-system/blob/main/run-scripts/run-kiosk-browser-forever-and-log.sh so that it will work to run in a non-locked down machine. I would also remove the piping of the output so you can see what's going on better. You basically just need the while loop wrapped around a call to run-kiosk-browser.sh
5. Run the above script to launch kiosk-browser running bmd, configure with an election if you are prompted to (you'll need to have a card reader plugged in, and either a printer plugged in or launch bmd with VX_APP_MODE='VxMark') 
6. Let BMD sit for 10 seconds on the "Insert Ballot Screen" it should then automatically close and kiosk-browser SHOULD relaunch however it instead seg faults when it closes and never relaunches. 

At least on Ubuntu 20 the seg fault seemed to happen when this window.kiosk.quit() was called: https://github.com/votingworks/vxsuite/blob/main/frontends/bmd/src/app_root.tsx#L1382 which itself calls app.quit() in electron: https://github.com/votingworks/kiosk-browser/blob/main/src/ipc/quit.ts#L14

**Comment by umbernhard** [comment]
I've successfully repro'd this on Debian.

**Comment by umbernhard** [comment]
Running with gdb (which is not very informative for an electron app, but I digress), it looks like the SIGSEGV is maybe coming from libudev. Investigating more...

**Comment by umbernhard** [comment]
Interesting, the crash doesn't happen until after a card reader is plugged in.

**Comment by umbernhard** [comment]
Yep, confirmed it's a udev problem 
![image](https://user-images.githubusercontent.com/2686765/155612630-4537a313-69d5-45ff-968e-8dd7f579d015.png)

**Comment by umbernhard** [comment]
Triggered by our usb-detection node module.

**Comment by umbernhard** [comment]
Running with node's [`segfault-handler`](https://httptoolkit.tech/blog/how-to-debug-node-segfaults/) module gives this traceback: 
![image](https://user-images.githubusercontent.com/2686765/155622563-69fc881b-7f44-40bc-9974-74e65f3f7a73.png)

**Comment by umbernhard** [comment]
I've replicated this issue on Debian 10, which is interesting. It may not be a udev problem, per se, but something about what the usb-detection module is doing.
