### ISSUE TITLE
Improving the repo's licensing

### ISSUE THREAD

**Issue by cjerdonek** [votingworks/vxsuite#1439]
While confirming this repo's license, I noticed that while the repo's `README` does say "GPLv3" at the bottom, the repo doesn't seem to contain a `COPYING` (or `LICENSE`) file, at least at the top level.

This page contains instructions on licensing a program under the GPL or one of its variants: https://www.gnu.org/licenses/gpl-howto.html

It includes, for example:

* Add a `COPYING` file.
* Give each file the proper copyright notices.
* Put a license notice in each file.
* Possibly including an "or (at your option) any later version" clause in the license notice, as discussed in the following linked page: https://www.gnu.org/licenses/identify-licenses-clearly.html

(Note there is a difference between the copyright notice and the license notice in each file.)

**Comment by cjerdonek** [comment]
PS - I think the other repos should also be checked. For example, even though `vxsuite-complete-system` may not itself contain much code, it contains some. Thus, it should probably contain a `COPYING` (or `LICENSE`) file, too.

**Comment by carolinemodic** [comment]
@benadida Can you own this?

**Comment by adghayes** [comment]
Added `LICENSE` files, `package.json` tage, rust metadata, and README descriptions for consistent GPLv3 only licensing across the repo's used in the certified system:

- `vxsuite`: #5558 
- `vxsuite-complete-system`: https://github.com/votingworks/vxsuite-complete-system/pull/402
- `kiosk-browser`: https://github.com/votingworks/kiosk-browser/pull/166
- `vxsuite-build-system`: https://github.com/votingworks/vxsuite-build-system/pull/136

I followed the pattern typical to GitHub, which varies a little from GNU's standard instructions:
- using `LICENSE` files rather than `COPYING` files - `COPYING` is just a GNU convention rather than a requirement, and `LICENSE` is the one that Github automatically recognizes
- using a `LICENSE` file at the root to cover the whole repo. some projects have license disclaimers in every file but it's not required and a root `LICENSE` is common practice
