### ISSUE TITLE
VxSuite: change download/upload language

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1443]
In a few spots, we use the terms "download" and "upload", which both is incorrect and feels incorrect. We're not uploading a ballot package. We're not downloading CVRs. We're loading a ballot package, we're saving CVRs. We should review our language accordingly.

/cc @beausmith @ginvdr for thoughts.

**Comment by mattroe** [comment]
We've modified some mentions, but not all of them. I think it's worth applying consistent & simple language across apps. I propose:

`Save` instead of `Download` or `Export`.

`Load` instead of `Upload` or `Import`.

@ginvdr @beausmith we were discussing this in a separate issue -- any concerns with this language?

**Comment by ginvdr** [comment]
I agree with these changes!  Much simpler and hopefully more intuitive to users.
