### ISSUE TITLE
Machine Configuration Wizard

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1448]
_Updated with details from discussion below as of 2022-03-15_

## Summary
The current steps to configure a machine are painful and require significant technical skill, making them not ideal for temp workers and contractors that help configure machines. More context: https://votingworks.slack.com/archives/CJU9MSC6S/p1645046374755609 

Longer term, we may want a graphical setup wizard. For now, we can use a text-based approach like the current `vx-admin` menu we have on `tty2`.

## Core Requirements

- In the admin menu (under tty2), show "Basic Configuration" as the first option, and label all other existing options as "Advanced". Visually separate out that one basic option from the others, to make it easier to differentiate between "things contractors need to do during setup" and other things.
- Basic Configuration should then lead the user through a linear wizard, defined below.
- Bonus points for standardizing the capitalization and other formatting of the menu (no periods after steps etc.) :)

## Stretch
- have a way to put a machine in "needs setup mode", which would be done for machine-0 before creating the image.
- in this setup mode, on first boot, without having to go into `tty2`, instead of starting X and kiosk-browser, automatically log in and run the text setup wizard.
- Make public signing key QR code easier to read off the screen -- this may be tricky in text mode, especially on Surface Go.

## Flow of Text-Based Setup Wizard

* prompt for machine ID
* prompt for confirmation of machine ID, then save it.
* prompt for time in a friendly way (e.g. a separate prompt for month, day, year, hour, minute) No need to prompt for seconds.
* show time and and ask for confirmation, then save it.
* generate signing key and display it as QR code, waiting for confirmation that it has been recorded
* generate TOTP secret and display as QR code, waiting for confirmation that it has been recorded 
* If possible, meaning if the data isn't too long, put machine ID, signing key, and TOTP secrets all into a single QR code, so just having the QR code around is enough to put all the data back together.
* wait for confirmation that QR code has been saved, then exit.

## Non-Requirements
- A graphical or wizard interface, the text menu is fine for now

**Comment by mcchilders** [comment]
@benadida I took a whack at defining this since I think it will be easy once people know what to do - please review?

**Comment by benadida** [comment]
> @benadida I took a whack at defining this since I think it will be easy once people know what to do - please review?

Thanks! I updated a bit, moving one requirement to stretch because it's a bit tricky.

**Comment by adghayes** [comment]
I think the way that this feature has been defined based on my feedback is excellent and would be an **enormous** help in production, making configuration faster and more accurate. Here are my suggestions, questions, and comments after reading the overview:

**Design Suggestions**:
- The confirmation prompt for Machine ID should be immediately after setting it. It's better for our flow to do only one task and confirm only one piece of information at a time. Was unsure if this was the plan due to the way the above was written up.
- Similarly, I think confirming date and time separately would be helpful. Both to ensure accuracy, but also because it's much more likely that the time could be set incorrectly and have to be reset. This is because it is sometimes the case that when you go to set the seconds, the minute value has already changed.

**Questions**:
- @benadida, for m13b, we will not be setting individual admin passwords on each machine, correct? If not, then password setting should be a part of the wizard.
- @carolinemodic @benadida, can / should / could setting the TPM keys be a part of this process?

**Comments**:
- Of the stretch goals, logging into the wizard on first setup is far more valuable. Less so because it is fewer steps, but because currently I or other VxPersons will have to enter the admin passwords and interrupt our flow on all 180 machines because the passwords cannot be shared with contractors.
- Any version of this will be super valuable and I am glad that it has been prioritized.

**Comment by benadida** [comment]
@adghayes setting the secure boot keys might be done as part of the imaging process. @umbernhard what do you think? Could our install stick update the secure-boot keys if they're not set?

@adghayes @umbernhard Here's an idea i'd love your thoughts on for passwords and such. What if, as part of the setup wizard, we did:
- passwordless login to the wizard (I have some ideas as to how we can do that securely, I'll explain below.)
- generate fresh `vx-admin` login password as part of the wizard
- bundle the TOTP secret, the machine public key, and the new `vx-admin` login password as *one* QR code so you only have to take one picture
- optionally, before showing the QR code, encrypt that data bundle with a milestone (m13b) public key, where we hold the private key, so that it's completely safe to have these QR codes lying around / seen by contractors.

Next, thought on how we can make the passwordless login work cc @jonahkagan:
- the goal is to keep tight security separation, specifically I'd prefer if `vx-ui` doesn't gain the permissions to write directly to `/vx/config`.
- in `/vx/config`, have a file like `DO_SETUP_WIZARD` that, if present, signals the need to run the setup wizard
- give `vx-ui`, the front-end user, the ability to sudo and run the `setup-wizard.sh` script. That script will first check for the presence of `DO_SETUP_WIZARD` and exit if it's not there.
- in the `vx-ui` bash login script, check for `DO_SETUP_WIZARD`, and if it's there, run the setup wizard instead of starting X and kiosk-browser.
- at the end of the setup wizard, remove `DO_SETUP_WIZARD` file from `/vx/config`
- in the normal `vx-admin` menu at `tty2`, add an option "do setup wizard on next boot" which creates the `DO_SETUP_WIZARD` file in `/vx/config`.

This approach would allow us to:
- test on machine 0 as much as we want, including trying to setup the wizard, run it, and go back to normal operation, and then right before creating an image from machine 0, we'd select "do setup wizard on next boot".
- on first boot of newly imaged machines, we end up right into the setup wizard
- when setup is done, we're in normal operation.
- no passwords needed by contractors, ever.
- though this gives `vx-ui` a little bit more power, that power is quite limited and non-existent unless the `DO_SETUP_WIZARD` file is there.

Would love your thoughts.

**Comment by adghayes** [comment]
Thoughts: 
- generating unique vx-admin passwords - great! as long as the password is displayed as a QR code
- merging all keys into one QR code - I think this would be better (fewer opportunities to save the keys incorrectly) but I don't have a strong preference. pick an easy delimiter if we merge! If the QR code is still character (#) based, is it possible that with more data it will get bigger and harder to read? I have a (yet) unfounded fear that the character based QR codes will be scanned incorrectly and lead to bad data
- if encrypting adds significant work, I think it is pretty unnecessary for this milestone. I have very little concern that contractors will save the code(s). They should *only* see the code(s) when they scan it into the app. They will have permissions to save it via the form but not to view that data later. In order to save the code for themselves, they would have to write it down or take a picture on their own phone when it is generated. An exception is if, in QA, we test all the TOTP codes. Contractors will have to see them to test them, and encrypting them initially is not going to affect that.
