### ISSUE TITLE
pv-based installer

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1502]
With secure boot + dm-verity, we need to make exact disk image copies. Testing using `pv` has worked. Now we need a simple live-USB that can perform this install easily.

https://docs.google.com/document/d/1aYYNsknSWnqHvR2NLte2jAz79veIt4kuISrrcLZoCxM/edit#

- [x] https://github.com/votingworks/vxsuite/issues/1762
- [x] https://github.com/votingworks/vx-iso/issues/23
- [ ] https://github.com/votingworks/vx-iso/issues/24
- [ ] https://github.com/votingworks/vx-iso/issues/25
- [x] https://github.com/votingworks/vx-iso/issues/26
- [ ] https://github.com/votingworks/vx-iso/issues/27
- [ ] https://github.com/votingworks/vx-iso/issues/28
- [ ] https://github.com/votingworks/vxsuite/issues/1828
- [x] https://github.com/votingworks/vx-iso/issues/39

**Comment by eventualbuddha** [comment]
Is this `dd` + `pv`? Or is this using something else to do the actual data copying?

**Comment by umbernhard** [comment]
`pv` does the data copying for us

**Comment by umbernhard** [comment]
Some open questions about this process: I have the install stick working correctly, using Arch Linux to generate a bootable `.iso`. I'm just taking their base installer and adding two files to it, a script to unpack, flash and verify that the flash was successful. The other file contains the expected hash of the disk. I have tweaked a few things in the default Arch iso (I added a systemd unit to drop right into a root shell), and I can tweak further to automatically run the script on boot. 

Currently I'm using [Ventoy](https://www.ventoy.net/en/index.html) as the base of the boot stick, as it provides an easy way to put isos on a thumb drive. It also provides a convenient way to sign the bootloader, though I'm still not sure how to address the Surface Go's. We may have to turn off secure boot for the provisioning stage for them.

**Comment by umbernhard** [comment]
This issue is largely addressed by votingworks/vx-iso. Awaiting some more testing there through the next week and then I can close.

**Comment by carolinemodic** [comment]
For m13b we moved fast and did the quickest thing that could get the job done for this which was the right priorities at the time. However as we look forward to m14 since we have a lot more time I want to reevaluate a bit of the problems we want to solve and work closely with myself, Matt B and Drew on the ideal process and needs for this tool. I think the next right step here is to review the needs, investigate some options, and then for @umbernhard to write up a quick tech spec on the proposed next steps technically. 

Some needs to keep in mind 
- We need a way to boot from a usb with some program or something on it to get a secure boot compatible image on our end hardware. This includes the: Lenovo Thinkpads for VxAdmin and VxCentralScan, Lenovo Ideapad Flex for the bmd, and surface go 2 and 3 tablets for VxScan. It is possible that we could change hardware in the future so as much as possible we want to minimize risk with other hardware not working. But the top priority is to have something that works with this set of hardware. 
- We need a way to create this bootable usb sticks when we all live on different sides of the country. 
  - Matt needs to be able to develop on the code for this, and test it.
  - Caroline needs to be able to create usb sticks with different potential release candidates of software to test on her hardware in QA and create the final versions of the usb stick with the final release candidate of the software for Drew. 
  - Drew needs to be able to take this final image and create usb sticks, potentially many of them, to have temps use to install the machines. 
  - A non-tech savvy temp needs to be able to use the created stick and very easily install the machine. 
  - While it is not the #1 use case the need for Caroline may also be done by all the other engineers on the engineering team. The easier it is for them to be able to test their code changes on a fully locked down, secure booted machine the more often they will do that, and the less bugs we will introduce that aren't compatible with a locked down/secure booted machine. There will always be some things different in that setting then in our standard dev env. 

- Also notable to the above requirements is the different dev setups we are all running with. Matt primarily develops on linux with virt-manager, Caroline and most of the rest of the engineering team primarily develops on a m1 arm based macbook with parallels linux virtual machines. While, if absolutely necessary, I can use my production hardware or purchase a specialized linux laptop for these tasks it would be strongly strongly preferable to be able to do everything I need to do from my Mac and/or the locked down hardware.

**Comment by benadida** [comment]
I'd suggest a couple of things:
- we should be resilient to device name changes
- we should be able to create one USB stick that can install, with a menu of options, any of the component images.
- i *think* it's okay if we can't create images on macs, as long as we can do so on a VM in AWS or something.

**Comment by umbernhard** [comment]
Question for @adghayes @benadida: is there a use case for having everything on one stick? It seems like that might cause confusion. I suppose it depends on your process.

**Comment by benadida** [comment]
> Question for @adghayes @benadida: is there a use case for having everything on one stick? It seems like that might cause confusion. I suppose it depends on your process.

Having the option would make just the logistics of managing a single release a good bit easier. Maybe not in the Bakery, I leave that to @adghayes, but there will be other use cases for this, e.g. upgrading machines in the field, dev/QA.

It seems like we can have our cake and eat it too on this, if the installer is flexible enough that it will present a menu if multiple images are present, and otherwise default to the only choice if there's only one.

Ideally, in a future v2 version, the installer will do a couple of additional things:
- detect the hardware and offer smart defaults, e.g. VxScan on the Surface Go.
- detect the machine type from pre-installed `/vx/config` and go with that if there's any ambiguity
- copy over config information from `/vx/config`

Those are just v2. For v1, just being multi-image capable would have helped me a lot in my dev.

**Comment by umbernhard** [comment]
So that is how it works after the stick is imaged the first time. You should be able to stick it in a computer and have two folders show up: Ventoy and Data. The ISO file goes in the Ventoy folder, and the machine image goes in the data folder.

**Comment by carolinemodic** [comment]
Product Spec: https://docs.google.com/document/d/1aYYNsknSWnqHvR2NLte2jAz79veIt4kuISrrcLZoCxM/edit#heading=h.bqlfgfbghbz9
