### ISSUE TITLE
VxAdmin: add write in selection option to L&A test deck

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1513]
Before an election the election workers run L&A, Logic & Accuracy testing to test that everything with the voting machine system works accurately. This includes printing a test deck with all possible contest options chosen at least once. So a ballot with 2 contests, each with 2 candidates running, will print 2 ballots in the test deck (per precinct). One with the first candidate voted for in both contests, and one with the second. Currently we do not print any ballots in the test deck with the write in option selected. We should add that. We will need to fill in the bubble, but we don't need to add any fake text to the line about who to vote for as it will just count as a write in. (This may change in the future with write-in adjudication). It would potentially look nicer if there was fake handwriting of "Write in" or something though.

**Comment by adghayes** [comment]
For contests with more than one write-in option, do we do this for each write in selection or only one of them?

I am making the assumption that we are doing the same for VxMark test deck.

**Comment by mattroe** [comment]
@adghayes the goal of a test deck is to confirm every possible selection / mark / bubble position can be tabulated accurately. When we implement this, we should include every bubble position in the test deck and therefore all possible write-in selections on multi-candidate contests. 

I'm not sure why the VxMark test deck size would need to be different? I still see value in including all possible write-in selections on the VxMark test deck as it proves that all possible on-screen marking options (instead of bubble positions) can be tabulated accurately.

**Comment by adghayes** [comment]
I agree that testing every bubble makes the most sense, but I still see a VxMark problem. The difference is that VxMark does not present 3 distinct write-in selections. Note the difference in UI: 

### VxAdmin

Here we have three truly different positions:

<img width="242" alt="Screen Shot 2022-07-11 at 7 37 23 PM" src="https://user-images.githubusercontent.com/37960853/178396566-04663a14-1105-4dbd-a61a-ef3b3c053e82.png">

### VxMark

There is only one position for a write-in:

<img width="450" alt="Screen Shot 2022-07-11 at 7 34 13 PM" src="https://user-images.githubusercontent.com/37960853/178396560-c32be0b3-532e-421c-a6b0-56d0744f78cc.png">

Other positions become available only if you fill out previous write-ins:

<img width="450" alt="Screen Shot 2022-07-11 at 7 34 35 PM" src="https://user-images.githubusercontent.com/37960853/178396567-8d25a89b-c6bc-4d3d-8575-dd3bb2899cc1.png">

## Question

Given the VxMark's behavior, I'm not sure what it means to "test all positions" on VxMark. I think that the appropriate testing is to only test a single write-in, because the printed ballot will always look the same with a single write-in (whereas on VxAdmin, there are as many ways to do it as there are write-in bubbles). Unfortunately, that lands us in a place where the two test decks are different sizes whenever there is a contest with multiple seats that allows write-ins.

**Comment by adghayes** [comment]
Different test deck sizes are acceptable, AFAIK, just annoying.

**Comment by adghayes** [comment]
Played with this on [a branch](https://github.com/votingworks/vxsuite/tree/drew/test-deck-write-in) and the drawback is, indeed, that the test deck counts are weird. This is correct:

<img width="518" alt="Screen Shot 2022-07-11 at 9 04 45 PM" src="https://user-images.githubusercontent.com/37960853/178413329-11709dcc-f725-4b34-bbb5-15566ec6e9bc.png">

**Comment by mattroe** [comment]
@adghayes thanks for the additional context. 

I just discussed this problem with Steve to get an election official expectation and he said that the BMD test deck should also have the same selection options / complete tabulation variants as the HMPB. This would also alleviate the confusion of having different test deck sizes.

**Comment by adghayes** [comment]
thanks for clearing this up! that makes implementation easier too. good to go.
