### ISSUE TITLE
Determine how to group "batches" for VxScan

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1520]
Currently the precinct-scanner considers every ballot its own batch, that is confusing in VxAdmin where you can see the ballots by Batch and Scanner. That view was added in. case someone runs a RLA. We should figure out with @mcchilders how we should actually be making batches out of the VxScan results.

**Comment by mcchilders** [comment]
Some context: The idea with batching is to group scans of ballots that correspond to the physical grouping of the paper ballots - on our central scanner this is easy, because you place a stack of paper ballots in the scanner tray all at once and it scans through the whole stack, so each stack = a batch. 
This is useful for RLAs, but the main point is actually to aid in troubleshooting; if you've scanned 10 stacks of ballots through the scanner and it turns out there's a problem with a single ballot/scan, it's much easier to delete/rescan a single batch than all the ballots you've done so far (which could be thousands) or sort through to find a single specific ballot. The subdivsion of large groups of ballots into smaller groups to help keep track of things (which our batch scanner does for free, since the scanner tray can only hold so many ballots) is a key piece of paper handling best practices, so batching on the scanner side just ensures that we're connecting the electronic ballot records to their paper counterparts in the same way.

So, for this ticket:
On our current product I would consider a "batch" on a precinct scanner to be everything scanned from polls open to polls close (which for our current clients is all ballots cast on e-day in that particular polling location). That's because all that paper falls into a single stack in a single ballot box, so there's no way to further differentiate it. 

Note that there are two features in the pipeline that should change this in the future, however:
- Once we start having a "suspended" state in between polls open and polls close - which we don't yet - I would end the current batch at suspension of polls, and start a new batch when polls are opened again. 
- When we start serving jurisdictions with enough ballots to warrant switching ballot boxes out throughout the day, I would end the current batch when the ballot box is replaced, and start a new one for the next ballot box (this will require some poll worker interaction, but assuming we want to warn the user that the ballot box is getting full and they should switch, we'll have an obvious place to do that).

**Comment by mattroe** [comment]
Closing will track as part of larger future project
