### ISSUE TITLE
Rethink Printing across all of our apps 

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1531]
We have struggled with various bugs and uncertainties in our printing strategies. A number of different ideas around printing have been brainstormed. We should spend some time trying different options and determining what the most robust and easy to develop with strategy for printing is and implement it across our various printing features. 

--- Details from a previous ticket --- 
Printing ballots in VxAdmin (and likely VxMark) depends on preventing React re-renders. It shouldn't.
Best example is in printing the test deck in VxAdmin.

We used PagedJS to render a bunch of ballots, and we are counting on that not being re-rendered before triggering a print. It's a bit tricky to solve this because PagedJS uses the DOM, so it's not obvious how to make that asynchronous work survive cleanly across re-renders.

**Comment by eventualbuddha** [comment]
Some discussion on the topic: https://votingworks.slack.com/archives/CEL6D3GAD/p1646834507614739.

**Comment by carolinemodic** [comment]
Related bug that we should aim to solve as a part of this ticket: https://github.com/votingworks/vxsuite/issues/2299

**Comment by carolinemodic** [comment]
We will also want to rethink the print time estimates in tackling this: https://github.com/votingworks/vxsuite/issues/1865

**Comment by adghayes** [comment]
@carolinemodic I think that the two other tickets closed in favor of this ticket are separate and not solved by, for example, the solution that @jonahkagan laid out recently. If you are thinking of this as a larger ticket, then grouping them is understandable.

The double print issue in #2299 is actually a Linux / CUPS level behavior, and won’t be affected by how we trigger printing in the app. The current ticket might prevent *other* cases of double-printing. The timing issues in #1865 would require getting print job ID’s from lp (instead of lpr) and tracking those in the app somehow. Definitely related, but different.

**Comment by carolinemodic** [comment]
Yeah I'm thinking of this as a larger/broader ticket. 
Related: https://github.com/votingworks/vxsuite/issues/2289

**Comment by carolinemodic** [comment]
Potential idea and demo from @jonahkagan https://votingworks.slack.com/archives/CEL6D3GAD/p1660580505853769

**Comment by adghayes** [comment]
It seems like we've established an approach in #2730, so here is the task list for this project AFAICT:

- [ ] #2730
- [ ] #2758 (< 1 day)
- [ ] #2759 (~ 4 days)
- [ ] #2760 (~ 3 days)
- [ ] #2761 (3 - 6 days)

**Comment by adghayes** [comment]
We have RETHOUGHT PRINTING. We are not prioritizing the print error handling work right now, and tracking that in votingworks/vxsuite-roadmap#86. Closing this ticket.

There is till more, non-prioritized work to do in terms of using the new approach to improve testing (e.g., testing exported PDF contents).
