### ISSUE TITLE
libs/ui has suprising behavior with snapshot tests

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1617]
Needs a good repro but I've noticed several times where I will add a new component to libs/ui or update a component, and in the frontend apps, snapshot tests that rely on completely different, unchanged components from libs/ui will regenerate the class ids causing a frustrating and annoying number of snapshot tests to change when making a very small PR.

**Comment by adghayes** [comment]
Repro'd this last week in #2793. 

Based on research I've done, we don't have a way to modify the murmur hash generated class names from `styled-components`. We can add a prefix, filename, or component name with `babel-plugin-styled-components`, but not affect the hash portion of the classname.

If we want to avoid this issue, I think that we would have to make a little snapshot utility that wrapped the regular snapshot but stripped out the `styled-components` classname. We could make it easier to target those classnames by using the Babel plugin mentioned above to prefix them all (from `libs/ui`).

I think the risks for this would be low (we're not looking at those classnames anyway!) but wondering if the complexity would be worth it. I lean toward yes, because the snapshot churn in frontends other than the one you're working in can be very confusing.

**Comment by adghayes** [comment]
I haven't heard about this being an issue in a while and, per my comment two years ago, I didn't see a good fix. So I'm going to close it unless @carolinemodic or @kofi-q still deem this a problem.
