### ISSUE TITLE
Convert jest snapshot tests to use jest-styled-components

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite#1622]
Snapshot tests for components using styled-components are really annoying because the generated class names change whenever you change styles. The jest-styled-components library fixes this problem.

https://github.com/styled-components/jest-styled-components

A few ways we could approach this:
- Add an import for jest-styled-components in all of our tests that have snapshots and then update all the snapshots
- Figure out a way to auto-import it using the jest config
- Convert tests that rely on snapshots to use more specific test assertions instead and use `toHaveStyleRule` when they want to actually test for specific styles

Example PR: https://github.com/votingworks/vxsuite/pull/1620

**Comment by eventualbuddha** [comment]
How mechanistic is the change? Could it be automated?

**Comment by jonahkagan** [comment]
Just tried to set it up in bmd, and it didn't work due to outdated jest and styled-components versions. I tried upgrading them but it was non-trivial since we'd also need to upgrade node.

So @eventualbuddha I guess in theory it's automatable, but might take some pre-work.

**Comment by taravancil** [comment]
Just noting that this is probably unblocked by #1735

**Comment by carolinemodic** [comment]
This may solve https://github.com/votingworks/vxsuite/issues/1617

**Comment by adghayes** [comment]
I did a little bit of digging. Good news: `jest-styled-components` can be easily set up in a package by simply adding the import the the `setupTests.ts` file. I haven't tried it in all the frontends but it works in `libs/ui` and `libs/election-manager`. On the individual package level, it does as it says it will - converts ambiguous, shifting class names to serialized class names with inspectable style rules. It would make our `libs/ui` snapshots much more useful, and I think we should at least implement it there ASAP (very low lift). 

Bad news: this is just a testing utility, so there's no impact on exports from a package. That means that there are still the `styled-components` generated class names on exports from `libs/ui`. So if you change a style on on a `libs/ui` component, it will change the class name in the snapshots in all the `frontends`, rather than serialize and inject style rules. Perhaps that's desired behavior, in that it will let us know where our `libs/ui` style changes are impacting the frontends?

That means that this also has no impact on [#1617](https://github.com/votingworks/vxsuite/issues/1617). However, I think that [#1617](https://github.com/votingworks/vxsuite/issues/1617) has mostly to do with `styled-components` generating classNames based partially on the _order of the components_ in the index file. Still a problem, but in most cases can be avoided by adding new components to the end of the index file.
