### ISSUE TITLE
Upgrade to React 18

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#1660]
## Summary
React 18 is out! We should upgrade once the dust settles a bit.
- Announcement: https://reactjs.org/blog/2022/03/29/react-v18.html
- Upgrade guide: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

## Requirements
- `@testing-library/react` has polished support for React 18, not hacks or workarounds.
- Each library and frontend depending on React should depend on React 18.

## Non-Requirements
- We should not use any of the new features in React 18, such as `<Suspense>` or other concurrent rendering, if we don't absolutely have to in order to make things work. We should do the minimal changes required to complete the upgrade before considering such changes.

## Tasks
- [ ] upgrade libraries (e.g. `libs/ui`)
- [ ] upgrade frontends (e.g. `frontends/bmd`)

**Comment by carolinemodic** [comment]
@eventualbuddha did we do this in the node upgrade or is this still pending?

**Comment by adghayes** [comment]
I took a stab the past couple days at upgrading React 18 and found that this is a massive and tricky project. I'm going to cut my losses for now and work on more critical changes, but I want to write up all the challenges to save the next person some time.

Upgrading to React 18 requires a number of other major or minor updates to meet peer dependencies

- `@testing-library/react` v14
  - `@testing-library/render-hook` is removed as `renderHook` is now a part of mainline RTL
  - `@testing-library/user-event` v14
- `react-router-dom`, `react-modal`, `react-textarea-autosize`, etc. minor updates
- `stylelint` minor update, which introduces breaking changes that need to be addressed
- corresponding type package upgrades

The changes to `React` itself are minimal and don't require almost any changes, only tweaking how we render our apps at the root of each app and in the print root for the print utilities. But the effects for testing are enormous. 
- `userEvent` becomes an entirely `async` API
- because of React 18's improved `setState` batching, many of our loading states become inaccessible during tests. it's no longer possible to `await screen.findByText('Loading')` in many places because it's never rendered within the test environment
- although the goal of the update is to reduce annoying test warnings, in some places it introduces new warnings where we were doing some actions triggering state updates outside of the UI and not wrapping in `act`
- fake timers get all messed up, but I couldn't identify exactly how

The big challenge is version conflicts. If there are multiple versions of react in any environment, it will cause problems. If there are multiple versions of `styled-components` in any environment, it will break theming. If there are mismatching versions of `react` or other `@testing-library` dependencies, you'll drown in errors. If there are mismatching versions of `@types` bindings or `@types` dependencies (esp. with `react-router-dom`), the linting will fail. 

Due to the version conflicts, it's not really possible to do this upgrade in a piecemeal fashion. I tried some of the testing-libraries before `react` itself, but that creates tons of test warnings. 

I'd love it if we eventually got this upgraded and I'm not sure when will be a good time to do that, but I think it's at least a week of work more likely two weeks of work, with some questions still unanswered. For now, I'll work on other things. I've leave my branch up for reference: https://github.com/votingworks/vxsuite/tree/drew/upgrade-react.
