### ISSUE TITLE
Augment VxAdmin test decks with pre-marked overvoted HMBP

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#1711]
Augment VxAdmin test decks with pre-marked overvoted HMBP

**Comment by adghayes** [comment]
@arsalansufi @beausmith, a few questions / thoughts:

1. Do we want to do a minimally overvoted ballot (a single overvote conflict) or a maximally overvoted ballot (every bubble filled)? Initially I thought minimally, but now I lean toward maximal because then it's very clear that it's overvoted.

2. There is a case where a ballot style is not possible to overvote. Specifically, a ballot with all candidate contests where the number of seats is greater than or equal to the number of candidates, and write-ins are not allowed. In this case, we won't print anything (because nothing needs to be tested).

3. If a candidate contest allows write-ins, it should always be possible to overvote if you fill in the write-in bubbles. However, there's currently not a way in the `HandMarkedPaperBallot` component to fill in [the bubbles next to the empty write-in lines](https://github.com/votingworks/vxsuite/blob/1c87d31c17b5e248b94f4ab7c967b6d7ace6236d/frontends/election-manager/src/components/hand_marked_paper_ballot.tsx#L512). If `votes` contains a write-in candidate, it appears as a new option entirely (see picture) which could extend the ballot over additional pages. Assuming we want to catch this overvoted case, seems like I'll need to change `HandMarkedPaperBallot`. I could add a prop that indicates that the empty write-in bubbles should be filled or we could handle the votes for write-in candidates differently. Do you have a recommended path here? 
<img width="505" alt="Screen Shot 2022-05-11 at 3 08 54 PM" src="https://user-images.githubusercontent.com/37960853/167958866-a897ad6d-578d-47f0-99ea-15124bc9b10c.png">

**Comment by beausmith** [comment]
Thanks for digging into this @adghayes. Here's my take.

The goal of having an overvoted ballot (and blank ballot) is to test that the ballot scanner will eject the ballot back to the voter. 

1. Ideally we have a "maximally" over-voted ballot such that it's easy to differentiate from other ballots. 
2. While the case you propose is possible, it's not likely that there will be a live ballot like this. But in the case that there is, it wouldn't be possible to print an overvoted ballot which the ballot scanner will eject. So, I'd suggest that we should not include an overvoted ballot because it would then effect the tallied results. (@benadida @ginvdr - Do you agree?)
3. Ooof. Yeah, the HMPB component wasn't built to be auto marked with write-ins. However, it's been floated that perhaps the BMD should be able to print a HMPB with the voter's choices… and thus with write-in values too. So, I'd say it's worth updating the HMPB component to support an array of data which includes write-in values. In the case of the over-voted ballot we should probably use something that stands out as non-human names: "APPLE", "BANANA", "COCONUT", etc.

**Comment by benadida** [comment]
While I see the benefit of a maximally overvoted ballot, I worry that this will not be seen as testing a real overvote – if I were paranoid, I would say "oh, your scanner detects when something is dramatically overvoted, but not when there's just one overvote."

I don't think we're going to know the right answer here, so we need to pick one. So, picking one: let's do the *minimally* overvoted approach, for the sake of actually testing a single overvote.

In terms of what we expect the testing to be, I suggest:
* L&A tester should make sure scanner rejects the overvote
* L&A tester taps "count anyways"
* ensure that the expected tally & actual tally both count the overvote.

I think we can ignore filling in the write-ins if we just do a minimal overvote.

If the election can't be overvoted, say there's only one question with 3 seats and 3 candidates, then skip the overvote ballot in the test deck. This will be rare.

**Comment by adghayes** [comment]
OK, thanks everyone for hashing this out. Given the above, we'll generate a ballot with a single, minimally overvoted contest on the first contest of the first ballot style where it is possible. If there is no such contest, we won't print anything. 

Since we will ignore filling in write-ins, we will miss some cases where the only possible way to overvote is with write-ins. I think these contests are not very rare and we've seen several of them with our customers. I just looked back at the election definitions for the 2021 primary and I found a couple on the second definition I looked at - uncontested single seats. Having an election with only such contests, however, I believe we've never seen and I agree seems rare enough to ignore.
