### ISSUE TITLE
Incorporate expected tally reports into VxAdmin test decks (instead of having them be printed separately)

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#1738]
Incorporate expected tally reports into VxAdmin test decks (instead of having them be printed separately)

And bring the button to print the expected tally report for all precincts out to the top-level L&A page such that the layout matches that described in [this proposal](https://docs.google.com/document/d/1M7n9fR7VE-qmcEqpW_lFVW3BCFZBwkbhppv9Q2_qJ2Y/edit#heading=h.42t8143wtvw)

Update: Moved the second piece of this task (button to print the expected tally report for all precincts) to its own ticket: https://github.com/votingworks/vxsuite/issues/1869

**Comment by adghayes** [comment]
@arsalansufi my thoughts on steps as part of this change:
- **Refactor to Create "Test Deck Tally Report" component.** There is already an Election Manager Tally Report component, but it appears we have opted not to use that component for the test deck tallies while we do use it for the zero report. I assume this is because the Test Deck Tally Report, unlike the zero report, is _only for testing purposes_, so we wouldn't want to confuse it with any other "Unofficial Results." Props: election, electionTally and precinct
- **Append Test Deck Tally Report to L&A Test Deck.** Seems like we are crossing the threshold from "Test Deck" to "L&A Package" so I think we should now rename some of the key components in `print_test_deck_screen.tsx` to make this clearer. 
- **Create "Print Full Test Deck Tally Report Button" component.** Can model this off of the zero report button component.
- **Place New Button Component on L&A screen**, removing current link to tally report sub-page
- **Delete `test_deck_screen.tsx`** which, despite it's name, is for printing tally reports
- **Update Testing**

**Comment by adghayes** [comment]
Note that currently, the Test Deck Tally page offers an option to save the report to PDF. That will be lost with this change. However, I don't think that matters because it's hard to imagine why exactly you would use that feature for test deck tallies.

**Comment by adghayes** [comment]
@arsalansufi & @adghayes discussed - the above plan of action is acceptable, and we plan to break it out into two different commits / merges: the first to make the TestDeckTally component and use it in the LNA package and the second to add the top-level button.

**Comment by adghayes** [comment]
@arsalansufi I just pushed my latest changes to the branch #1851 - haven't rebased since you might do that later anyway. Notes:

-  Overall printing, timing, & formatting seem to work in single and all precincts case
- `print_test_deck_screen.test.tsx` test failing due to weird timeouts
- L&A test in `app.test.tsx` needs to be updated for number of print jobs, also giving problems
- I renamed variables in the files for my own understanding, but not terms in the UI
- Haven't meaningfully touched logging (do we log for each print job?) 

Let me know if you have questions that I can help with as you debug!

**Comment by arsalansufi** [comment]
Moved the second piece of this task (button to print the expected tally report for all precincts) to its own ticket: https://github.com/votingworks/vxsuite/issues/1869

Closing this issue out accordingly!
