### ISSUE TITLE
Split the contents of the Tally tab into separate Tally and Reports tabs

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#1739]
Split the contents of the Tally tab into separate tabs, as most recently described [here](https://docs.google.com/document/d/1jBoQqIE7IEr3G_zGfAkl0gDD2kammjIDzpOf7K7StsI/edit#heading=h.z08sgskaryix) and [here](https://docs.google.com/document/d/1jBoQqIE7IEr3G_zGfAkl0gDD2kammjIDzpOf7K7StsI/edit#heading=h.ctocg4kff0y5)

**Comment by adghayes** [comment]
Couple Q's as I dig in, trying to understand the spec doc:

- _“Mark Tally Results as Official“ button moved to the Full Election Tally Screen._ - am I correctly understanding this to mean that the "Mark Tally Results as Official" button should move to the report detail page (pictured)? Sidebar: by default, this page hides and doesn't show the report preview. I've found that mildly disorienting in general, but if it's the page where we're supposed to mark the results as official it seems like it would help to default to showing the results. 
<img width="1259" alt="Screen Shot 2022-06-17 at 9 56 37 PM" src="https://user-images.githubusercontent.com/37960853/174423426-54794bd3-0a0b-43e0-85fa-9de84c4532b4.png">

- We're adding the "Printed Ballot Reports" to the reports tab. Can I confirm that it will _remain_ on the Ballots tab? If so, I will make sure the "Back" link from the "Printed Ballot Reports" page goes back according to router history.

**Comment by arsalansufi** [comment]
> am I correctly understanding this to mean that the "Mark Tally Results as Official" button should move to the report detail page (pictured)?

That's my understanding!

> it seems like it would help to default to showing the results

Agreed!

> We're adding the "Printed Ballot Reports" to the reports tab. Can I confirm that it will remain on the Ballots tab?

Great q - I'm not sure about this one. I think this is worth a question in #vxsuite-prod-eng. While @beausmith's less available, we can maybe get an opinion from Roe. My hunch is that we shouldn't allow printing the report from two places and should only have the report live on the Reports tab.

**Comment by arsalansufi** [comment]
Also just wanted to note that https://github.com/votingworks/vxsuite/pull/1966 may affect your work / create conflicts for you if you've already started writing code for this. Though https://github.com/votingworks/vxsuite/pull/1966 introduces a feature flag, no need to gate this change behind that flag.

Lastly, definitely feel free to table this for your hardware threads @adghayes - this change isn't blocking me!

**Comment by adghayes** [comment]
## Design Input Needed
cc @arsalansufi @beausmith @mattroe 

### Tally Screen
Changes: Removed all components unrelated to CVR management, as specified in the docs.  Added clarifying header.

<img width="1512" alt="Screen Shot 2022-06-27 at 6 41 23 PM" src="https://user-images.githubusercontent.com/37960853/176069145-d33f3b9c-f1d1-4b9c-957b-3a2e032361b8.png">

### Ballots Screen
Changes: `Printed Ballots Report` button removed.

<img width="757" alt="Screen Shot 2022-06-27 at 6 41 50 PM" src="https://user-images.githubusercontent.com/37960853/176069194-9dbaeb24-478e-4baa-b1ee-4c97e360c5c5.png">

### Full Election Report Screen
Changes: `Mark Results as Official` button and functionality moved to this page. Only appears on _full_ report, none of the others.

<img width="758" alt="Screen Shot 2022-06-27 at 6 41 42 PM" src="https://user-images.githubusercontent.com/37960853/176069172-24e195fd-e6e2-4535-b20b-90bb35c0d3bb.png">

### New Reports Screen
Contains: All tally report links, Export Results button, and Printed Ballots Report link. I am least sure how to arrange this screen. How do we want to arrange the 2 miscellaneous buttons on top and then start the main reports section? A few possibilities:

Example 1:
<img width="757" alt="Screen Shot 2022-06-27 at 6 53 39 PM" src="https://user-images.githubusercontent.com/37960853/176072238-04f1b4c8-881f-4541-af5b-e554d9a0081b.png">

Example 2:
<img width="757" alt="Screen Shot 2022-06-27 at 6 57 59 PM" src="https://user-images.githubusercontent.com/37960853/176072273-6685c1be-a8e4-4a92-992b-0868012f2ffc.png">

Example 3:
<img width="1511" alt="Screen Shot 2022-06-27 at 6 41 12 PM" src="https://user-images.githubusercontent.com/37960853/176069112-96fc938e-8160-4223-9f95-e368b6d15e48.png">

**Comment by adghayes** [comment]
More options with the "other" buttons small, I like these more, especially examples 4 & 5:

Example 4:
<img width="1512" alt="Screen Shot 2022-06-28 at 8 03 06 AM" src="https://user-images.githubusercontent.com/37960853/176213495-3ef3cacd-f4d5-465c-962f-1eb10ac3d8d0.png">

Example 5:
<img width="1512" alt="Screen Shot 2022-06-28 at 8 05 42 AM" src="https://user-images.githubusercontent.com/37960853/176214083-5af75273-bd52-4446-bc20-55de00baeb3b.png">

Example 6:
<img width="1512" alt="Screen Shot 2022-06-28 at 8 02 37 AM" src="https://user-images.githubusercontent.com/37960853/176213519-a92ded25-9bf3-4e35-952e-11def0db5e91.png">

**Comment by beausmith** [comment]
Had a sync-chat with Drew. He took notes and will update screens for review.

**Comment by adghayes** [comment]
Based on feeNotes from our discussion, some of which are straightforward changes and some which require some follow-up with other members of the team:

### Tally Screen
- Importing and Removing CVRs is the main action on this page, so those should be kept centrally and the other buttons can be separated away. External file related buttons and manual data related buttons could be grouped separately under sub-headings.
- Based on feedback that red buttons are alarming and may draw attention to buttons we actually want to be mostly ignored, instead of Import = Grey, Remove = Red we should try Import = Green, Remove = Grey
- Because list of CVR files could get long, import button should be above it. Remove button could be above or below, below would be even more de-emphasis
- Because "CVR" terminology may not be as familiar in the industry, we may want to de-emphasize it. Discuss with Ginny & @mattroe 

### Ballots Screen
- We removed the "Printed Ballots Report" link but still have the "0 official ballots" text. Perhaps that text sets up expectation there is a report? Or the preview would be more valuable on the new Reports page. Discuss with Ginny & @mattroe 

### Reports Screen
- We don't need the "View" on the report link buttons. The header in those columns can just be "Report" instead of "View Tally"
- Title of page = "Election Reports"
- Make two most important / common buttons - "Full Election Tally" and "All Precincts" report green buttons
- Party chart has "Full Election Tally" link under it - is this a duplicate? Should remove if so, and possibly replace with an "All Parties" report
- Reorder top buttons. View Full Election Tally first, then "Save Results File" on same row. Next, printed ballots report

**Comment by mattroe** [comment]
@adghayes:
- I like all these takeaways. Follow the green button!
- What is the workflow where an administrator wants to know the overall count of the ballots, but not the absentee/precinct/ballot style counts? I can think of it as a ballot accounting workflow requires that other context. My intuition is to remove the text entirely on that screen and force users to go to the Printed Ballots Report where that context is already available.
- I don't see a strong reason to change the CVR language at this point. It's also easy to update the copy in the future if we see a problem with the language.

**Comment by adghayes** [comment]
@mattroe @beausmith @arsalansufi, please give this 2 minute screenshare a look to provide feedback on the split screens before I submit a PR! Unmute to hear narration.

[split-tally-tab-rev2.webm](https://user-images.githubusercontent.com/37960853/177250511-51863168-f3f0-474d-a6dd-49c9c8ae376c.webm)

I kept the "X official ballots" language next to the "Printed Ballots Report" button because it seemed like it needed a little framing on the reports page (where every other report is a tally report) but can remove it. Also note that I changed some additional copy around the ballot tables that we have not discussed, but seemed unintuitive to me.

**Comment by mattroe** [comment]
@adghayes This looks great! Sensible choices on the reports copy including the decision to include [test/official] ballots.

**Comment by arsalansufi** [comment]
+1 this all looks great to me @adghayes!

**Comment by beausmith** [comment]
@adghayes Solid work! Thank you for doing this work.

A couple comments…

### typo?
<img width="818" alt="Screen Shot 2022-07-06 at 03 51 08" src="https://user-images.githubusercontent.com/28444/177451729-833fc5f0-f920-4a0f-b4bc-423b9dea6b70.png">

Is there is a copy/pasta typo here? Shouldn't this text simply be "Manually Entered Results" for consistency?

---
### Add some separation
<img width="816" alt="Screen Shot 2022-07-06 at 03 58 34" src="https://user-images.githubusercontent.com/28444/177451738-ef068c22-871e-401f-aa98-c0ccd013d812.png">

Can we separate the Printed Ballots report from the Full Election Tally Report with a "Printed Ballots" heading?

---
### Simplify Modal
<img width="817" alt="Screen Shot 2022-07-06 at 04 17 35" src="https://user-images.githubusercontent.com/28444/177453723-aa18c2fa-94ac-4ab5-a685-29884089cab4.png">

The modal to mark as official has too much text and doesn't indicate that this is a point of no return. Let's update this copy to:

> **Mark Tally Results as Official?**
> Once marked as official, tallies can no longer be imported or modified, and unofficial reports will be marked as official reports. This action can not be reversed.
> (Cancel) (Yes, Mark Tally Results as Official) <-- red button


---
### Missing Button?
<img width="817" alt="Screen Shot 2022-07-06 at 04 38 05" src="https://user-images.githubusercontent.com/28444/177456354-0ef39c30-4b71-4ba0-be83-284e4afbf673.png">

Where did the "Remove CVR Files" button go? Shouldn't this button exist here, but be disabled like the others? 

---
### Move Button
Let's change the "Clear All Results" button to "Remove All Tallies and Results" and place this button just under the title of the page.

---
### Add Title to Modal
<img width="816" alt="Screen Shot 2022-07-06 at 04 49 29" src="https://user-images.githubusercontent.com/28444/177457649-5d9cab67-ba64-4897-b1da-28000c236805.png">

This modal needs a title. How about this reworked copy…
> **Remove All Tallies and Results?**
> Do you want to remove the 2 imported CVRs files, the external results file (sems.csv), and manually entered data? All reports will be unavailable without this data.
> (Cancel) (Yes, Remove All Tallies and Results) 

---
### Standardize on "import"
There is some inconsistency between the terms "loaded" and "uploaded" and "imported". We should standardize on "imported". Because we are not on "the web" and we are working "locally" we should not be "uploading" or "downloading" rather we are "importing" files into the computer and "exporting" from the computer.

**Comment by adghayes** [comment]
Thanks for all the feedback @beausmith! I synced with @mattroe and we decided to limit the scope of this work to how the pages are arranged, but leave other copy edits in modals or subcomponents for a later UI revision. Here I'll quote reply the changes you suggest that are "Former Copy" and we're leaving for another PR and the ones I incorporated or tried:


Former Copy

> ### typo?
> <img alt="Screen Shot 2022-07-06 at 03 51 08" width="818" src="https://user-images.githubusercontent.com/28444/177451729-833fc5f0-f920-4a0f-b4bc-423b9dea6b70.png">
> 
> Is there is a copy/pasta typo here? Shouldn't this text simply be "Manually Entered Results" for consistency?

My instinct was to not have a section for a single button, and that I was grouping the button along with the others at the top as sort of "general election reports." I'm going to remove the configuration timestamp because I agree that's confusing, but I will leave the heading out for now because I tried it out and it looks a little strange to me.

<img width="758" alt="Screen Shot 2022-07-07 at 9 29 16 AM" src="https://user-images.githubusercontent.com/37960853/177825386-7e4449b3-d6e5-431b-b9ad-af2fb866bbc1.png">

> ### Add some separation
> <img alt="Screen Shot 2022-07-06 at 03 58 34" width="816" src="https://user-images.githubusercontent.com/28444/177451738-ef068c22-871e-401f-aa98-c0ccd013d812.png">
> 
> Can we separate the Printed Ballots report from the Full Election Tally Report with a "Printed Ballots" heading?

Former Copy

> ### Simplify Modal
> <img alt="Screen Shot 2022-07-06 at 04 17 35" width="817" src="https://user-images.githubusercontent.com/28444/177453723-aa18c2fa-94ac-4ab5-a685-29884089cab4.png">
> 
> The modal to mark as official has too much text and doesn't indicate that this is a point of no return. Let's update this copy to:

Former Copy

> > **Mark Tally Results as Official?**
> > Once marked as official, tallies can no longer be imported or modified, and unofficial reports will be marked as official reports. This action can not be reversed.
> > (Cancel) (Yes, Mark Tally Results as Official) <-- red button

The "Remove CVR Files" is only there before the election is marked as official. After it is marked as official, it is replaced by the "Clear All Results" button which clears all files. That is the old behavior, but with the next change you suggest, I'll leave the "Remove CVR Files" button on the screen at all times and only disable it when there are official results. This will be more consistent with the rest of the screen, and help indicate that the action is substantially different than simply removing all CVR files.

> ### Missing Button?
> <img alt="Screen Shot 2022-07-06 at 04 38 05" width="817" src="https://user-images.githubusercontent.com/28444/177456354-0ef39c30-4b71-4ba0-be83-284e4afbf673.png">
> 
> Where did the "Remove CVR Files" button go? Shouldn't this button exist here, but be disabled like the others?

Done.
> ### Move Button
> Let's change the "Clear All Results" button to "Remove All Tallies and Results" and place this button just under the title of the page.

Former Copy
> ### Add Title to Modal
> <img alt="Screen Shot 2022-07-06 at 04 49 29" width="816" src="https://user-images.githubusercontent.com/28444/177457649-5d9cab67-ba64-4897-b1da-28000c236805.png">
> 
> This modal needs a title. How about this reworked copy…
> 
> > **Remove All Tallies and Results?**
> > Do you want to remove the 2 imported CVRs files, the external results file (sems.csv), and manually entered data? All reports will be unavailable without this data.
> > (Cancel) (Yes, Remove All Tallies and Results)

Former Copy
> ### Standardize on "import"
> There is some inconsistency between the terms "loaded" and "uploaded" and "imported". We should standardize on "imported". Because we are not on "the web" and we are working "locally" we should not be "uploading" or "downloading" rather we are "importing" files into the computer and "exporting" from the computer.
