### ISSUE TITLE
Investigate alternate options to Ventoy

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1762]
Time-Boxed at 1-2 days max lets spend a bit more time investigating our different options for Ventoy as a part of vx-iso and expand on those in the vx-iso spec: https://docs.google.com/document/d/1aYYNsknSWnqHvR2NLte2jAz79veIt4kuISrrcLZoCxM/edit# 

Pros of Ventoy: Easy to install on a bootable USB, easy to use different ISO files and different IMG files on the same usb with it. Pretty simple UI to chose the ISO. If we had different ISOs for saving and flashing an image it would work well with that. 

Cons of Ventoy: The UI screen is a little weird/confusing, would be nice to have nothing there. Does require downloading and installing a program, not compatible with macOS. 

Ultimately I don't actually think any of the cons are major so I lean toward Ventoy but we should understand the options a bit better.

**Comment by umbernhard** [comment]
@carolinemodic so the biggest con here is that if we ditch Ventoy we won't be able to easily mix and match isos and images. Without Ventoy, the iso has to be the first blocks on the disk, so if it ever changes the whole stick will have to be reimaged (well, at least the first partition). That might be completely fine if vx-iso is stable, which it probably will be?

**Comment by umbernhard** [comment]
Ditching Ventoy would also require us to figure out Secure Boot. We might have to pick a different distro to base the iso on, because Arch isn't signed by the Microsoft keys by default. For anything that's not a Surface, we can make it work because we'll have our own keys to sign with. We _might_ be able to submit vx-iso to MS to get it signed (there's a github process for that somewhere), or if we go the MoK route on Surfaces it might be sufficient to use the MoK keys. This will definitely take more than a day's worth of work to figure out, whereas we get it for free with Ventoy.

**Comment by umbernhard** [comment]
We can definitely customize Ventoy's UI, since it's just a GRUB menu. https://www.ventoy.net/en/plugin_theme.html

**Comment by umbernhard** [comment]
We are going to stick with Ventoy for v1. We may revisit this task for future iterations.
