### ISSUE TITLE
VxScan: Hardware diagnostics

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1816]
We should mirror the diagnostics screens already implemented on the other machines:

- https://github.com/votingworks/vxsuite/blob/main/apps/mark-scan/frontend/src/pages/diagnostics/diagnostics_screen.tsx
- https://github.com/votingworks/vxsuite/blob/main/apps/admin/frontend/src/screens/diagnostics_screen.tsx
- https://github.com/votingworks/vxsuite/blob/main/apps/central-scan/frontend/src/screens/diagnostics_screen.tsx

The page should, for now, live behind sys admin auth as we're expecting diagnostics to be run centrally. We can explore supporting running diagnostics at precincts at a later time.

As a reference point, this is what the VxMark diagnostics page looks like:

<table><img src='https://github.com/votingworks/vxsuite/assets/12616928/0ceb779b-eba4-4165-a035-679bdef5c7ce' alt='vxmark-diagnostics' width=400 /></table>

The main components to test on VxScan are the printer and the scanner. For the printer, we have existing test-page print functionality that we can use: https://github.com/votingworks/vxsuite/blob/main/apps/scan/frontend/src/components/printer_management/print_test_page_button.tsx. Open question what the test for the scanner should look like.

**Comment by adghayes** [comment]
@carolinemodic some handoff notes:

I don't think @mattroe and I formally landed on what to include in the VxScan diagnostic page, but roughly speaking:

**Computer Storage**
How much memory is available on the computer - this has already been added to the other machines. You can copy some of the code in the apps, which uses utilities from `libs/backend`.

**Printer Diagnostic** 
- Descriptive status readout
- Test page printing (component already exists) 
- Button to enter the reloading flow (the component should be roughly re-usable from the election manager flow)

**Scanner Diagnostic** 
- Status readout
- Test scanning, which is going to take a little R&D. In VxCentralScan, we simply scan a blank page and confirm that we read a blank image (in the rust library). However, that test working depends on the sort of images that the Fujitsu produces, which don't have much of a black margin. I'm not sure what the margins on the PDI scanner look like. If they have substantive black margins, the test will always fail, and we'll have to update the diagnostic to crop out more margins or do a smarter approach entirely. 
- MSD calibration, I haven't thought about how this should work yet, or if it should be in election manager flow, sys admin flow, or both

**Speaker Diagnostic**
- Press a button to test a sound and then modal pops up to confirm or deny that you heard it

**Touchscreen Diagnostic**
TBD

All of the above could / should be done across multiple PRs. Some miscellaneous notes:

- The components for the diagnostic reports exist in `libs/ui` so they are re-usable in the frontend and as printouts from the backend.
- The default "Computer" component has a "Battery" section, which is moot on VxScan because we don't have battery data. The same goes for VxMarkScan. As a follow-up, we should remove that section.

I very much left this diagnostics project 3/4 completed and am eager to sync about it from an eng. perspective, or to hash out the remaining product questions.

**Comment by adghayes** [comment]
Closing this in favor of #5193 and #5194 as the specific remaining diagnostics.
