### ISSUE TITLE
VxAdmin: Hardware diagnostic report

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1817]
## Requirements

Election Manager should be able to print a hardware diagnostic report that lists power status (plugged in, battery remaining), card reader connected status, and printer information (toner, paper).

Details:
* in advanced options, offer "hardware diagnostics"
* hardware diagnostic screen displays above listed information on screen
* a `print` button enables printing of this information, plus machine ID, election name and ID, and current time.

**Comment by adghayes** [comment]
I believe we can close this issue.

The final product differs a bit from @benadida's original write-up (almost two years ago) in that:
- we don't include card reader connection status, since we are certifying on built-in smart card readers
- we don't include election name since it may be printed outside of an election context. in the precinct equipment a readiness report with this data is required, but my reading of the guidelines suggest that's not required for the election manager report
