### ISSUE TITLE
VxAdmin: indicate progress on how many precincts you've loaded results from

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1939]
It would be nice if VxAdmin told you what percent of precincts you had imported so you knew how far you were in the night 

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/CJU9MSC6S/p1654653901808419?thread_ts=1654653901.808419&cid=CJU9MSC6S

**Comment by benadida** [comment]
part of other task for loading CVRs (can't find ticket right now).

**Comment by adghayes** [comment]
Noting that I'm skeptical of the feature insofar as it relates to multi-scanner precincts. We would indicate that you've loaded results from a precinct but not know whether we've loaded from all scanners. 

I'm going to leave open for now because I think there is something we could do for users in terms of indicating or summarizing progress, but I think it should remain unprioritized until we have more demand / clarity, probably from eventual larger customer who could inform a more complete feature.
