### ISSUE TITLE
vxadmin: L&A package BMD ballots showing up without seal image

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1947]
I've seen this in the past, it's sometimes that the image isn't loaded yet when the page is rendered. Hard to see with manual testing on screen, only reproducible when you actually print.

**Comment by adghayes** [comment]
I noticed today that it's not just the seal - the formatting of the whole ballot appears a little different.

### BMD Test Ballot from VxAdmin
<img width="505" alt="Screen Shot 2022-06-23 at 9 30 55 AM" src="https://user-images.githubusercontent.com/37960853/175365594-a46bea8c-166e-40e9-899f-0b193dd4cb89.png">
### BMD Test Ballot from VxMark
<img width="506" alt="Screen Shot 2022-06-23 at 9 29 37 AM" src="https://user-images.githubusercontent.com/37960853/175365602-43c77b67-c2f3-4b2b-be4c-6521716c7a89.png">

**Comment by adghayes** [comment]
Currently we support seals either as image URLs or as plain SVG which is injected into the ballot. Is that still something we want to support? It only applies to one of our fixtures, but otherwise it doesn't appear that we use it:
https://github.com/votingworks/vxsuite/blob/2b493dff0c449ce9be026885d17336a9a8dd9441/libs/ui/src/bmd_paper_ballot.tsx#L286-L307

**Comment by adghayes** [comment]
Self-assigned this after checking with @arsalansufi and will submit PR soon. Easy fix.
