### ISSUE TITLE
Usage of white and transparent color in card assets looks a bit off

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#2022]
See https://github.com/votingworks/vxsuite/pull/1993#issuecomment-1162739340

**Comment by beausmith** [comment]
These graphics are intended to be used on [Screen components with a white background `<Screen white>`](https://github.com/votingworks/vxsuite/blob/main/libs/ui/src/screen.tsx#L4). If/when we desire to use them on the grey backgrounds then I'll be happy to edit/update these graphics to work on grey backgrounds.

**Comment by arsalansufi** [comment]
Nice I figured as much! We do have one use on a screen with a gray background (the recently added "remove your card" screen):

![image](https://user-images.githubusercontent.com/12616928/176046612-0030ee0d-068d-4d60-8a73-d06cc8baaf93.png)

@beausmith Could we get an updated asset for that screen or would you prefer we use a white background for that screen?

**Comment by beausmith** [comment]
@arsalansufi - Thanks. This "Successfully Authenticated" screen should be updated to:
- Make this screen a full-screen modal (no footer)
- Update the background to be white.
- Update the title to "Successful Authentication" (no period)
- Update the text to "Remove card to continue."
- The space between the graphic and the heading seems off.

Ok, this was enough feedback for me to just edit some code… but unfortunately my VM is currently messed up so I couldn't run the tests/etc. I made a WIP commit and am hoping that you or @adghayes might be able to use it to push a PR?

https://github.com/votingworks/vxsuite/compare/beau/remove-card-ui-update

**Comment by adghayes** [comment]
@arsalansufi and I can sort out which of us incorporates these changes, but I want to explain some of the design choices I made before changing them. I left the background gray and included the election footer for consistency with the rest of the auth flow. After the `SetupCardPage`, all the other auth screens are grey and include the election footer. This includes both the keypad screen and the invalid screen. I thought at the time that popping to white and dropping the footer for a prompt could be slightly more jarring.

I agree that it looks better with more spacing - we kept it limited to be more consistent with the lock screen page.

The icon definitely looks better on white!

Visuals below, to see the flow with this PR and currently.

Updated Screen:

<img width="1512" alt="Screen Shot 2022-06-28 at 8 16 14 PM" src="https://user-images.githubusercontent.com/37960853/176344080-74480474-fd3a-41dd-a843-0f9e368a4f0d.png">

Updated Flow:

[screen-capture.webm](https://user-images.githubusercontent.com/37960853/176344486-82d75e33-c976-4375-ae93-1b9aafe9c4bb.webm)

Current Flow:

[screen-capture (1).webm](https://user-images.githubusercontent.com/37960853/176344901-e3edf1df-a741-453e-ade9-58d0e438e344.webm)

**Comment by beausmith** [comment]
@adghayes - Thanks for the reasoning and screen casts! I'm sorry that I am not currently running the full experience and noticing this inconsistency. 🤦  This is something that always bothered me when designers suggested something without taking the full user experience into account.

My suggestion… The keypad screen, invalid screen, and successful auth screens are all "modals" where we should focus the users attention on the action/decision they need to do in order to proceed and move everything else out of the way. In order to have a consistent flow, I would like to suggest that we update the keypad screen and the invalid screen to have the same modal design as the successful auth screen: white background and no footer. 

However… if you disagree for any reason (and want to keep the grey background and footer on those screens)… I ask that you keep the basic layout of the page contents that I pushed… and replace the graphic the attached which has a transparent background:

![remove-card-transparent](https://user-images.githubusercontent.com/28444/176759851-6d1e4082-dddd-4b31-bccb-11d095000bea.svg)

**Comment by adghayes** [comment]
Sounds good @beausmith! I will give it a try with the white & footers removed from all those screens, I suspect that that will be better. If it looks good, I'll merge it.
