### ISSUE TITLE
nh-accuvote VxCentralScan: old WIA demo shown

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2067]
When programmed with the [state ballot converted definition](https://github.com/votingworks/vxsuite/blob/main/libs/ballot-interpreter-nh/test/fixtures/amherst-2022-07-12/election.json), VxCentralScan shows the old write-in adjudication demo flow for write-in ballots. This should not be shown as we have moved WIA to VxAdmin.

Possible solutions:
1. Remove `WriteIn` as a `centralScanAdjudicationReason` in the converted output to prevent stopping of write-in ballots on VxCentralScan. 
2. Fix VxCentralScan to not show the old write-in adjudication flow with the write in adjudication reason. Kill it!

**Comment by benadida** [comment]
I've got a PR started to remove the old WIA flow, but it's a large change and possibly risky. I think removing `WriteIn` as an adjudication reason is the safer path, since we want to remove those adjudication reasons at the scanner level anyways long term. My read of the `nh-demo` code indicates that nothing depends on those adjudication reasons being set.
