### ISSUE TITLE
VxMark: no audio in headphones

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2117]
## Description
There is no audio when using headphones on a locked down production VxMark [using this image](https://s3.console.aws.amazon.com/s3/object/votingworks-machine-images?region=us-west-2&prefix=2022-07-nh/2022-07-08-vxmark.img.lz4) for the NH demo.

**Comment by carolinemodic** [comment]
I have been doing some testing with VxDev where I know I definitely had audio working at one point. I can get speech synthesis installed and on both current main and on the m13b release if you call speechSynthesis.getVoices() from the console you can get the speech voices to be returned as expected. However no actual audio ever seems to get emitted despite this on either m13b or current main.

**Comment by carolinemodic** [comment]
I was able to get audio outputting again if I manually killed the festival server and restarted it

**Comment by carolinemodic** [comment]
Although it is giving errors about "unknown voice cmu_us_slt_artic_clunits"

**Comment by carolinemodic** [comment]
Although it is giving errors about "unknown voice cmu_us_slt_artic_clunits"

**Comment by carolinemodic** [comment]
Ok on more investigation I think there are two issues
1. At some point between m13b and current main (likely the electron upgrade) something breaks where speechSynthesis.getVoices() no longer returns voices properly on current main when it worked for m13b. 
2. Separately on my VxDev machine I had an issue where for some reason the festival server was running on port 1314 but was not working and not outputting any audio, this was discoverable by running `sd-say "test"` in the command line and hearing nothing. When I manually killed the process running on port 1314 and reran festival in a console window locally `festival --server` it was able to start working and emitting audio again. I don't know if this was caused by a real bug or if something I did in testing got things in a borked state.

**Comment by carolinemodic** [comment]
This does appear to stop working when the electron/node upgrade takes place. 
Repro steps: 
Checkout the code in kiosk-browser before the upgrade
```
git checkout 14976d3
make install 
DISPLAY=:0 KIOSK_BROWSER_ALLOW_DEVTOOLS=true KIOSK_BROWSER_URL=http://localhost:3000/ KIOSK_BROWSER_FILE_PERMISSIONS='o=http://localhost:3000,p=/**/*,rw' KIOSK_BROWSER_AUTOCONFIGURE_PRINT_CONFIG=../vxsuite-complete-system/printing/printer-autoconfigure.json yarn start
```

Then in the console run 
```
speechSynthesis.getVoices() # see empty array
window.location.reload() 
speechSynthesis.getVoices() # after running 2 or 3 times you should see voices returned
```

Following the steps above after checking out the code after the upgrade i.e. `git checkout f473e50` will never have voices returned in the steps above. 


You have to reload to get the voices for confusing reasons, but that is how our code currently works.

**Comment by benadida** [comment]
I've confirmed @carolinemodic's exploration – and I've not found a workaround to get the voices to show up in Electron. Meanwhile, speech dispatcher is still working great via `spd-say`.

Given that this has long been the wobbliest part of our setup, it's time to fix it. We should:

- add an API for speech to kiosk-browser that forwards to `spd-say`
- ensure that API has parameters for volume and rate.
- update our app to call this new kiosk browser API instead.
- when the API implementation speaks a new piece of text, make sure to cancel existing speech with `spd-say -C`.

I've not been able to modify volume or rate with parameters to `spd-say`. For volume, however, here's something that's worked for me in VM:

`amixer -q -D pulse sset Master 40%`

I recommend we have an API with a volume setting with 20 stop points (that's enough to cover VVSG and common sense).

I also recommend that state (current volume, current rate) be maintained in the React app, fed to the API with every speak command. That way we'll be compatible with just about any underlying system API if it has to change, and not build state management at a low-level.

**Comment by adghayes** [comment]
The `amixer` command solves this for volume, but I was really hoping to be able to set `rate`. Because the volume and rate controls work with other modules, I think this is a festival issue. Not sure if festival just doesn't support it or if it's a bug, but I'm not going to sink any more time into that and just limit our controls to volume.
