### ISSUE TITLE
VxAdmin: make it easier for customers to save ballot PDFs to send to third party printers

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2146]
## Summary
Right now, there are two ways to export PDFs of ballots to send to a third party printer and they both have usability issues:
1. Exporting ballot package: the zip of all ballot styles includes test & live mode ballots, as well as extraneous information for customers such as the layout .json files.
2. Saving ballot PDFs from the ballot proofing/printing view: this requires that a user save ballot PDFs individually by ballot style, which can be overly onerous/error prone requiring dozens of individual downloads.

The priority of this issue depends on whether customers print ballots with a third party printer or on-demand via VxAdmin for m14 (which is also dependent on m14 paper weight testing).

## Requirements
An administrator should be able to export to a USB drive the PDFs of all ballot styles for a given ballot mode in a one-click manner.

**Comment by adghayes** [comment]
Clarifying the requirement "for a given ballot mode"... Do we want to include test & sample ballots? Absentee I am assuming yes. I see the use case here as primarily for official ballots.

**Comment by mattroe** [comment]
@adghayes good question. This is definitely primarily going to be for official ballots so exporting of test/sample ballots doesn't need to be a hard requirement. 

I think the implementation of this could actually work well in tandem with the proposed implementation of https://github.com/votingworks/vxsuite/issues/2175 where there is a `Save as PDFs` option in the `Print All` modal. That would also provide us the flexibility for saving other ballot types for as a byproduct.

**Comment by adghayes** [comment]
My gut is that we should keep the two features separate. I think that `Save as PDFs` should be a top-level button and as easy to find as possible. It's not intuitive to me (as an imaginary user) that you should go through a `Print All` modal to export PDFs for a third-party printer. I also think it would make the actual implementation more convoluted rather than less to combine them.

It's not really much additional work or complexity to allow PDFs of test/sample ballots to be exported. To me it's more the question of whether we want our users to have that option or not. Advantage - more flexibility. Disadvantage - risk of exporting the wrong type of PDFs at the wrong time. Small risk.

**Comment by mattroe** [comment]
SGTM. The ballots tab is going to get pretty busy, but we can solve that in the future.

Let's provide the flexibility for all ballot types as we had a documented ask for sample ballots included in ballot package for non-VxAdmin printing: https://github.com/votingworks/vxsuite/issues/1472

**Comment by adghayes** [comment]
@mattroe, here's a video for your UI feedback:
[export-ballot-pdfs-rev1.webm](https://user-images.githubusercontent.com/37960853/181312319-14f5560d-7051-4cc0-b569-e766fb4612ac.webm)

**Comment by mattroe** [comment]
@adghayes overall UX and feature flow looks great. can handle copy nits later
