### ISSUE TITLE
Merge `nh-demo` into `main`

### ISSUE THREAD

**Issue by taravancil** [votingworks/vxsuite#2148]
## Summary
Merge `nh-demo` into main, which will require addressing merge conflicts, writing new tests (to meet test coverage requirements), and to fix any existing tests that are breaking in `nh-demo`.

## Tasks
- [x] #2149
- [x] #2153
- [x] #2158
- [ ] #2186
- [ ] #2187
### Polish / Clean Up 
- [ ] #2169
- [ ] #2168
- [ ] #2167

**Comment by carolinemodic** [comment]
Some notes from https://github.com/votingworks/vxsuite/pull/2049

- I removed the OvervoteCombinationScreen, this was written a long time ago and hasn't been active in our code ever, so I think we should be ok to just kill it, @benadida has more context on what this is. 

- The way I handled removing duplicate CVRs is inconsistent so we should probably rethink longterm. I made the ballotID a unique ID in the database, so when we are actually saving CVRs they are deduplicating through that, but when we are showing the import dialog and just previewing how many duplicates there are we are instead checking against a set of ballot IDs stored in memory. We should probably just stick with one of those approaches. 

- The URLs in the admin service should probably be renamed something more generic instead of all nested under write-in.

**Comment by carolinemodic** [comment]
Long long term we will want to store the tallies and manually entered data / external SEMS data into the admin service as well.

**Comment by mattroe** [comment]
@taravancil in addition to WIA, we also created a slight variation for overvote handling (no voter override, different copy) that is specific for NH. we're going to need a way to program the precinct-scanner for that overvote handling based on the election definition.

**Comment by mattroe** [comment]
We also want to land this at some point: https://github.com/votingworks/vxsuite/pull/2076

**Comment by taravancil** [comment]
Summary of where this work stands:

The admin service changes are merged in, and I'm feeling pretty good about test coverage there. There is probably still some refactoring we'll want to do, but we can punt that for now.

The scan service changes #2158 are also in a good state, and that branch is up for review.

Changes to election-manager are in a branch `nh-demo-election-manager`, and still require a number of changes to fix linting, other broken tests, and to add new tests. Tracked in #2186.

Finally, we'll need to pull in the precinct-scanner changes. #2187, this has not yet begun, but those changes are minimal relative to the other pieces we had to pull in.

The other tasks listed above are not required to get `nh-demo` merged into main, however we should do them eventually. If others agree, we might want to consider moving them out of this ticket and into standalone tasks.
