### ISSUE TITLE
Reevaluate how to transfer write in images from scanning to VxAdmin

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2360]
For the nh-demo we quickly implemented the ballot image transfer embedded within the CVR files. We should reevaulate this approach for the longer term, and do some load testing to see how big of files we can handle with this, or other, approaches and make sure we are comfortable with that load for a nh pilot.

**Comment by eventualbuddha** [comment]
What numbers are we expecting for this? Put another way, what number of write-in images should we be testing with? Are we only transferring ballot images for sheets with write-ins or for everything?

**Comment by mattroe** [comment]
@eventualbuddha realistically between 1,000-5,000 and probably closer to the smaller end of the scale

**Comment by mattroe** [comment]
Current plan is to revisit this when we address VVSG-CVR/CDF work.

**Comment by adghayes** [comment]
The switch to CDF format does not require that we change how we're transferring write-in images. CDF allows them to be embedded just as we're doing now. This means that the work can be decoupled, and can happen in either order.

To help me with contest - what are the advantages are there in not embedding? cc @eventualbuddha @carolinemodic.
- Avoids file size limitations
- Allows one to manually inspect ballot images in CVR 

There are disadvantages with switching, namely the complexity that all our CVRs, fixtures and in the wild, are now directories rather than single files. @mattroe do you know if that's the case with competitors?
