### ISSUE TITLE
Lenovo Thinkpads are spuriously having issues booting on locked down production

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2396]
https://votingworks.slack.com/archives/CJU9MSC6S/p1660691822344369
https://votingworks.slack.com/archives/CEL6D3GAD/p1660574418673599

**Comment by carolinemodic** [comment]
Testing has surfaced that plugging a usb hub into the laptop prevents this problem from occuring. Just plugging a card reader in does not, but a usb hub does seem to solve the problem

**Comment by mattroe** [comment]
@adghayes has identified what appears to be a completely reliable mitigation by delaying boot by 1s through a BIOS config change: https://votingworks.slack.com/archives/CEL6D3GAD/p1662079791975949?thread_ts=1662071580.334889&cid=CEL6D3GAD

**Comment by umbernhard** [comment]
Disabling dm-verity does not resolve the issue. It also does not appear to be an actual thermal problem, as blasting the device with compressed air makes no difference. 

It appears to likely be a firmware race condition introduced by booting with EFISTUB. My hypothesis is that there's some hardware that isn't initialized in time when the linux kernel boots, so the kernel gets spurious readings off a thermal sensor and crashes. This is why delaying startup by even a trivial amount of time solves the issue, and also why booting with GRUB works as well: the extra delay allows the hardware to get initialized before the kernel tries to read sensor data. 

Because of this, and because of the effectiveness of the BIOS setting workaround, I'm closing this issue.
