### ISSUE TITLE
WIA: solution for non-official candidate hand-adjudicated (overvoted) ballots

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2585]

**Comment by adghayes** [comment]
@mattroe, part of this work is working the manual write-in results into the scatter report. Does that scatter report need to be broken down by manual, "scanned" (adjudicated on screen), and total? Like in our regular reports after #2624. That would be a good bit of work.

I'm unsure if it's a requirement because it makes less sense to audit in hand recount because all of them - both adjudicated manually and on screen - are already adjudicated by a person.

**Comment by adghayes** [comment]
@mattroe and I decided to not do the manual breakdown in the scatter report for now, and to make a different ticket to track.

**Comment by adghayes** [comment]
@mattroe @beausmith @carolinemodic take a look at the current manual write in experience. The fundamentals are there so I am going to start writing testing.

[manual-write-ins.webm](https://user-images.githubusercontent.com/37960853/194417852-bbd9f56e-9808-4006-ab98-7a8261fe8984.webm)

**Comment by beausmith** [comment]
@adghayes - Functionality looks good. One question: When adding a manual write in text value, do you also restrict the addition of names matching official candidates as well as the previously added write ins?

**Comment by mattroe** [comment]
Functionality LGTM. As we discussed, we can circle back on the manual breakdown on the write-in report if we learn it's necessary / if we have time.

**Comment by adghayes** [comment]
@beausmith, it also blocks you from adding official candidates, forgot to specify in the video.
