### ISSUE TITLE
WIA: write-in report says adjudication has not been completed when it has

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2595]
When you adjudicate everything for official candidates on the write in tally report for that contest it says “adjudication of write in votes has not been completed for this contest” even though it has been completed for that contest.

**Comment by adghayes** [comment]
@mattroe, related question - what do we we want the behavior to be when adjudication is only partially complete for a race? Currently we show the partial results. Do we want to wait to show results until adjudication is complete?

**Comment by mattroe** [comment]
@adghayes I think initially we can keep it simple and let partial results be shown. Long term we can decide if customers would prefer to only allow this report at all to be seen once adjudication is complete.

**Comment by adghayes** [comment]
Is it acceptable to just make this a copy change? Instead of "Adjudication of write-in votes has not been completed for this contest" we could say "No write-in votes have been adjudicated for non-official candidates for this contest."

We can certainly make the other change (different message for each case), but I don't want to complicate the data and the feature if a copy change suffices. Once we have more feedback / clarity about what's needed for this report after NH, we can circle back.

**Comment by adghayes** [comment]
@mattroe connected and we agreed it is OK to just not show contests that have no non-official write-ins adjudicated (which is what @mattroe had in mind). That's easily doable and we'll get it done before code freeze. But it interacts a good bit with #2649 so I will circle back once that is merged.
