### ISSUE TITLE
VxScan: check that mark threshold overrides are respected

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#2614]

**Comment by carolinemodic** [comment]
As context in this task the mark thresholds define the percent of pixels that must be filled in in a bubble in order to count a specific vote as counted. This is defined by default in the election definition, but there is an ability to override that default in the UI through the admin interface. I suspect this override feature might be broken in the NH codepath currently (but I could be wrong) so we want to look into that and fix it if it is broken. 

In order to test this you will need to configure services/scan to run as a precinct-scanner, there is an HTTP mock scanner interface you can use for this. Then you can front frontends/precinct-scanner and test scanning ballots, and overriding the threshold. You should be able to quickly test it by testing a ballot that should scan and seeing the CVR has tallies, then overriding the threshold to something like .99 and seeing that nothing was tallied, or overriding it to like 0.01 and seeing a bunch of overvotes most likely. It might be a little hard to test with the sample ballot images I'm not 100% sure how filled in those bubbles are.

**Comment by carolinemodic** [comment]
This works!
