### ISSUE TITLE
WIA: reconciliation of double votes

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2738]
### VVSG Requirement
> 1.1.4-I – Write-in reconciliation
> The voting system must be capable of gathering and recording write-in votes within a voting process that allows for reconciliation of aliases and double votes.
> 
> Reconciliation of double votes means handling the case where, in an N-of-M contest, a voter has attempted to cast multiple votes for the same candidate using the write-in mechanism.

### Product Requirements
* If after adjudicating the contest, multiple write-in votes in an N-of-M contest on one ballot are adjudicated to the same candidate, the tally report should only count one vote for the candidate.
* Tally reporting should consider the "extra" votes for the same candidate as undervotes.

Example on a vote for three:
- write-in: `Bob`
- write-in: `Bob`
- write-in: `Bob`

The CVR would include a vote for three write-ins and no under/overvotes. After adjudication, tally reporting should consider this case as 1 vote for `Bob` and 2 undervotes for the contest.

**Comment by kofi-q** [comment]
**[Postponed]**

This will involve updating the existing tally computation logic to include write-in adjudication data, to enable de-duping votes across both official contest options and write-ins.

Since we're planning changes to tally computation, including moving the logic to the backend, we're blocking this task on those changed happening first, to avoid code churn.

Slack thread with additional discussion [here](https://votingworks.slack.com/archives/CEL6D3GAD/p1669924924035269).

**Comment by adghayes** [comment]
Closed as part of #3428
