### ISSUE TITLE
Non-zero totals

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2800]
VVSG 1.1.3-B:

> The voting system must not enter the voting mode until all steps necessary to isolate test data from election data have been performed successfully and all vote counters have been zeroed. An attempt to open polls with non-zero counters: must be recorded in the audit log and an election worker must be clearly notified of the event

**Comment by adghayes** [comment]
We are not implementing a similar warning for the BMD currently per @mattroe, although would definitely have to do so for a combined marking + casting device.

**Comment by adghayes** [comment]
We have implemented on VxScan in #2809, but we need to remember to implement this on VxMarkScan (or whatever) if we get to that. Leaving open for however you want to track @carolinemodic @mattroe.

**Comment by adghayes** [comment]
@mattroe based on my reading of 1.1.3-B, I believe we need to add a warning to VxMarkScan if polls are opened with non-zero vote total. Even though VxMarkScan is not tallying votes, it is still a voting device which enters a voting mode so I believe this applies.

VxMark can be avoided because it's not included in certification.

@mattroe let me know if you agree or disagree with my interpretation, depending on which I will implement this or not.

**Comment by adghayes** [comment]
Implemented where relevant, because it was deemed not necessary for VxMarkScan (now VxMark).
