### ISSUE TITLE
bmd ballots scanning slower then hmpb

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#337]
When scanned together in one batch bmd ballots seem to scan slower then hmpb. 
Video: https://drive.google.com/file/d/16wYag9GrIFCtpCDVOu4pUB5SH215dyx9/view?usp=sharing 
Backup Export: https://drive.google.com/file/d/1mY7jpjD1r4krz6g_byVjky3Jpbuqnnsx/view?usp=sharing

**Comment by eventualbuddha** [comment]
This is likely due to the change to grayscale using a different threshold for binarizing than whatever the "lineart" scanning mode did. As such, some "blank" pages show up with a bit more than 5% black and some less. More, and we waste a whole bunch of time (~300ms) trying to find a QR code. Less, and we consider the page blank and don't look for a QR code.

**Comment by eventualbuddha** [comment]
Closed by #340
