### ISSUE TITLE
Scanners: support tabulation of long paper lengths

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#3848]
specific length TBD based on hardware testing; most likely 22"

align with vxdesign lengths

**Comment by eventualbuddha** [comment]
Tested scanning a 8.5x24" blank sheet with `libs/custom-scanner/bin/demo`'s autoscan feature. The scanner acted as normal and I got these images from it:
| Side A | Side B|
|-|-|
|![Image](https://github.com/votingworks/vxsuite/assets/1938/92ac8230-4b24-4754-aa3a-c119645e4585)|![Image](https://github.com/votingworks/vxsuite/assets/1938/ea67db22-912d-4817-9386-f4d354adc8cc)|

I'd like to find a way to print an actual 24" or 22" ballot that can be scanned, but this result indicates that we likely can scan 22" ballots with our current setup.

**Comment by eventualbuddha** [comment]
Also tested with the PDI PageScan v5 using their `scan_demo` program. I had to make a change to the program to set the `PAGE_SIZE` tag on connecting to the scanner:

```cpp
pdiscan_error = PdSetTagLong(scanning_handle, PDISCAN_TAG_PAGE_SIZE, PD_PAGE_SIZE_MAXIMUM_SIZE);
```

Once I did that I was able to scan the same 8.5x24" sheet I used with the Custom scanner. It wasn't very clear whether the whole thing was scanned properly because of the bitonal scanning instead of grayscale, so I drew on the front of the sheet as you'll see in the images:

| Side A | Side B |
|-|-|
|![Image](https://github.com/votingworks/vxsuite/assets/1938/cd8a3f8a-e86e-472a-88a8-6817c1c352ba)|![Image](https://github.com/votingworks/vxsuite/assets/1938/6ed416db-171f-428a-aae5-40ab847e9c10)|

The vertical line is apparently just my scanning unit. I've tried cleaning the sensor glass but the line doesn't go away. It's unrelated to the long sheet.
