### ISSUE TITLE
VxMark: Alarm when printer cover is opened while polls are open

### ISSUE THREAD

**Issue by kshen0** [votingworks/vxsuite#3873]
The takeaway from [All Things 12.1](https://docs.google.com/document/d/1Zp9_qVn5fzC9FgMiD2RyGemOEYXIFxlRdAA2vzpub0o/edit) was that we need to add an alert on VxMark when the printer/scanner cover is opened when polls are open (in an activated state).

See the doc above for all the specific requirements we must meet for this issue. It notably includes:

- The visual styling requirements we have implemented on VxScan warnings
- An audio alert over the VSAP speaker that measures 60db output from 4 feet away. The nature of the sound is not specified in VVSG, but it should be a continuous alert until a user authenticates (see below).

The alarm should not go off in an activated state when an a user (pw, em, sa) is authenticated to enable unjamming the printer. As part of this change, we should add copy to the jam screen on VxMark to prompt poll workers to authenticate before unjamming.

The alarm should also be disabled and screen as soon as a user authenticates.

Slack discussion of how we got here: https://votingworks.slack.com/archives/C062Y0ZFKFT/p1715781514012669

**Comment by kshen0** [comment]
On pause since we may be getting subcomponents that won't include the optical sensor/plastic cover

**Comment by amcmanus** [comment]
@kofi-q, I've done some initial tests with this via the command line, and it will just be a set of `amixer` commands to enable playing via the on-board speaker, even if headphones are connected. 

1. `amixer set -c0 Speaker 100% unmute`
2. play the alarm
3. `amixer set -c0 Speaker 0% mute`

If the headphones are connected, the above settings will result in the alarm playing through both. If we'd rather not have it also play in the headphones, it will require adding the appropriate `amixer` commands to mute headphones, play the alarm, unmute the headphones. Those commands would be: 
```
amixer set -c0 Headphone 0% mute
amixer set -c0 Headphone 100% unmute
```

The `amixer` commands will need to be run as the `vx-ui` user since it owns the audio session used by the app.

**Comment by kofi-q** [comment]
Finally managed to test this on a prod image and the audio output switching between headphones and speaker is working great and it's just about hitting the 60 dB mark - although, VxAustin is fairly echoey and the readings might be higher here.

I'd already cranked up the gain on the source audio file pretty high, so if we end up needing to raise the volume, I wouldn't recommend applying software gain to avoid distorting the sound, but rather look into [bumping up the pulseaudio sink volume](https://github.com/votingworks/vxsuite-complete-system/blob/f284a31c9f49d5243a5ab5102262cd1563710fb7/config/xinitrc#L29) at startup and editing the startup chime audio file to reduce the gain there (since I think that was what made it necessary to lower the volume in the first place)

Also, if we do the above, we'd also want to bring the screen reader audio volume back down a bit, since we [increased it](https://github.com/votingworks/vxsuite/commit/e5fe7a3516f25dd4c9ec8594341b6ba4bb7bfa89) account for both the reduced startup volume and the new headhpones.

https://github.com/user-attachments/assets/0d77f80b-583c-4fc3-96f8-eb81fe47c02c
