### ISSUE TITLE
Some interpretation fails with InvalidPage error

### ISSUE THREAD

**Issue by kshen0** [votingworks/vxsuite#4694]
We previously thought this would be fixed by https://github.com/votingworks/vxsuite/pull/4663 but the issue persists. There might be a deeper problem with interpretation.

**Comment by kofi-q** [comment]
Looks like this got fixed by the change to force-interpret as a BMD ballot. Mocked out the print-scan flow to feed the "printed" ballot PDF back in the interpreter as an image and everything worked fine. Will do another sanity check with the real hardware later this week, just in case there's a driver problem at play.
