### ISSUE TITLE
USB drives with volume titles that contain spaces can crash the app

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#4833]
USB drives with volume titles that contain spaces can crash the app

Issue automatically created from Slack feedback reported by drew: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1714773835294109?thread_ts=1714773835.294109&cid=CJU9MSC6S

**Comment by arsalansufi** [comment]
Copying from Slack:

> I bet this is because we don't wrap variables in the relevant shell scripts with quotes, e.g., https://github.com/votingworks/vxsuite/blob/663ec51255d7b0c8c1b8499bbdb24fb935eb8f0a/libs/usb-drive/scripts/unmount.sh#L25

**Comment by adghayes** [comment]
Looked into this a little. We would fail on those commands where we don't wrap the mount point, but we actually fail before, when we compare the mount point against the regex and it doesn't match because our regex doesn't include spaces.

But the main point is that this isn't actually about volume titles, it's about mount points. And our system never uses mount points with spaces. As a result, this problem is only possible in development in a situation where the volume title has a space, is mounted outside of our system to a mount point with a space, and we try to eject it from within the app. 

Even so, I'm going to fix it because it could avoid future confusion and is easy.
