### ISSUE TITLE
VxMark: System diagnostics production QA

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#4905]
These may just be an artifact of VxMarkScan system diagnostics not yet being finished. But am documenting these finds anyway so that we remember to check them after completing system diagnostics implementation. We noticed all of the following behaviors in a production environment, so they may be specific to production.

- [ ] “Save Readiness Report” on sys admin “System Diagnostics” screen sometimes crashes the app.
- [x] Accessible controller listed as not detected on sys admin “System Diagnostics” screen.
- [x] System diagnostics screen sometimes shows up as a blank white page. Seems to happen more often when a voter session is active. Might be a red herring.

**Comment by kshen0** [comment]
> “Save Readiness Report” on sys admin “System Diagnostics” screen sometimes crashes the app.

Still trying to reproduce this.


> Accessible controller listed as not detected on sys admin “System Diagnostics” screen.

Root cause is use of `execFile` to execute `ps aux | grep controller[d]`. `execFile` doesn't support pipes[0] so I'm switching to `exec`.

[0] "Since a shell is not spawned, behaviors such as I/O redirection and file globbing are not supported." https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback

> System diagnostics screen sometimes shows up as a blank white page. Seems to happen more often when a voter session is active. Might be a red herring.

This happens because when in a voter session we use react-router to navigate the ballot flow. We also use react-router in the system diagnostics page. When we navigate from eg. `/contest/:id` in the ballot flow to the system diagnostic flow, the `Switch` instance in the diagnostic flow doesn't know what to render for `/contest:id` and renders a blank page. This doesn't crash the app.

We could solve for this in a few ways:
* when auth changes, reset path to `/`. This is simplest but obviously results in loss of history
* create a history `Context` to track history for each react-router instance
* upgrade to react-router v6 (we are on 5) and use the `useNavigate` hook https://reactrouter.com/en/main/hooks/use-navigate
* move one or both flows off react-router

Given the likelihood that users will need to run a system diagnostic exactly in the middle of a voter session I am hesitant to invest a lot in supporting this flow. Thoughts @arsalansufi @mattroe ?

**Comment by arsalansufi** [comment]
Thanks for all the notes @kshen0! Regarding the react-router problem:

> This is simplest but obviously results in loss of history

Does this just mean that the voter will be returned to the start voting screen instead of where they were before the sys admin opened system diagnostics? If so, I think that's totally fine. (I wouldn't however want that to be the case when a poll worker interrupts a voter session.)

If we're thinking about this in the same way, I also think it'll only be the case that you lose history if a sys admin actually opens the the system diagnostics page. (I'm imagining that we'd add a react-router `<Redirect>` at the end of both react-router `Switch` blocks that redirects to `/` for any unknown route.)

**Comment by kshen0** [comment]
Correct, after sys admin auth, the voter will return to `/` ie. the "Start voting" page

**Comment by arsalansufi** [comment]
Cool - I'm okay with that and think that the simple solution here is just fine! You're right that it'll be rare in practice that a voting session is interrupted by a sys admin opening up system diagnostics

**Comment by kshen0** [comment]
https://github.com/votingworks/vxsuite/pull/5119 and https://github.com/votingworks/vxsuite/pull/5188 address the last 2 issues. I'll put a little more time into reproducing issue 1 and report back.

**Comment by arsalansufi** [comment]
Sounds good @kshen0! It's possible that that issue is no longer relevant as we found these issues long ago while prepping for the Los Angeles demo

**Comment by arsalansufi** [comment]
Adam verified that saving the readiness report works on the latest image, so I'm going to close this out!
