### ISSUE TITLE
VxMark: Reverse printer icon arrow

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4932]
Printer icon arrow goes up, but on VSAP we print down

**Comment by jonahkagan** [comment]
Where is the card reader on the VxMark? I can easily change the orientation of the insert card image

**Comment by kofi-q** [comment]
Just re-reading this - thought it was about the card insertion image, for some reason. Looking at the date it was opened, I'm guessing this was referring an older iteration of the UI. Here's the current print flow for reference:

![Screenshot 2024-10-30 at 10 31 58](https://github.com/user-attachments/assets/7a503c1f-da42-44ac-a190-09ebd3a25df8)

Could bring back the printer graphic if we think it's useful  (context is that I removed it while adding the "don't remove the ballot" messaging because I thought the image distracted from the instructions and added to the confusion that led to people pulling out the print)
