### ISSUE TITLE
VxMark: Generalize blank paper error screen

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4933]
Printing a ballot onto a previously printed sheet expectedly causes interpretation to fail. But the UI indicates that the “ballot page is blank”. We shouldn’t assume that a page being inserted in the wrong orientation was the cause. We should have a more generic message that covers multiple possible explanations.

Update: This will likely be taken care of as part of https://github.com/votingworks/vxsuite/issues/4812, which has us perform a scan  right after paper insertion and will detect if a sheet is not blank. See the [Figma](https://www.figma.com/design/hvboQDWXqE1PbpGbWfb9iU/[VxMarkScan]-Printed-Ballot-Scan%2FRe-Scan-Flows?node-id=2-78)

**Comment by kofi-q** [comment]
This might actually still be an issue, since the ballot re-insertion flows that we addressed earlier are separate from this one. Here's the potentially misleading screen for reference (shown after an attempted print/scan and detecting either a blank page or unreadable QR code):

![Screenshot 2024-07-31 at 15 04 41](https://github.com/user-attachments/assets/a1720458-dc4a-4170-a42e-210670f73011)
