### ISSUE TITLE
bug: accessible controller up-down arrows not working on write-in

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#497]
For some reason up-down arrows on a keyboard in a VM do work...

**Comment by carolinemodic** [comment]
I believe this bug has been fixed since we last cut vxsuite-complete-system. We migrated the buttons in question here to a shared Button component since then so I believe that somehow fixed this bug
Repro Steps:
Install Clean Ubuntu on Lenovo Thinkpad
Install / Build vxsuite-complete-system
Run BMD and see bug reproduce
Update Vxsuite to most recent code on main and rebuild
Run BMD and see bug no longer reproduce

https://zube.io/files/votingworks/353636a208ce32f78c77410639735975-img_1409-3.mov
