### ISSUE TITLE
VxScan: Update USB removal screen to align with alarm screen/sound requirements

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5049]
Part of VVSG2 12.1-C

While we're at it, we should make sure that all our error messages meet the VVSG2 alert UI requirement (7.3-K)

**Comment by mattroe** [comment]
@kofi-q the core of the work for this issue is to adjust the frontend presentation of this screen to be in the style of other errors/warnings such as the one you just implemented on VxMark for the alarm: https://github.com/votingworks/vxsuite/pull/5369

This is the only other screen that needs to have an audible alert associated with it and I think it's fine that the audible alert is the same as the VxMark sound you implemented for the printer-scanner cover alarm.

Like the VxMark alarm, this audible alert only needs to sound off during an activated state (polls open), but we still want to highlight usb removal in other states as already implemented.

We have a few choices in terms of how we implement the sound:
1. add a short alert sound (like other sounds on vxscan) when this happens in all states
2. have no sound in non-activated states, but have a short alert noise in the activated state
3. either 1 or 2 in non-activated, and a printer-alarm-like implementation for the activated state that requires poll worker intervention to silence

For the sake of simplicity, while still meeting the requirement, I suggest we just implement 1, but open to thoughts on other audio implementations.

**Comment by nbhatia823** [comment]
https://github.com/user-attachments/assets/9efc17ec-1bd0-4ef9-88ee-97b24f6101f0

Does "USB removal screen" reference this screen where VxScan is in open to ballots and then the USB gets disconnected?

**Comment by kofi-q** [comment]
@nbhatia823 I think that's the one - briefly started taking a look and I believe it's the screen that corresponds to [this file](https://github.com/votingworks/vxsuite/blob/main/apps/scan/frontend/src/screens/insert_usb_screen.tsx)

**Comment by arsalansufi** [comment]
Yup that's the correct screen @nbhatia823!

**Comment by mattroe** [comment]
@nbhatia823 looks like we did the audio change in https://github.com/votingworks/vxsuite/pull/5469 but not the visual change or am I missing something?

**Comment by mattroe** [comment]
@nbhatia823 ignore this comment - I took a closer look at VVSG and we don't strictly need to change the visual presentation for this. I also don't want it to feel too much like an error state if you remove a USB post-configure pre-polls-open.
