### ISSUE TITLE
Check that VxComputer's USB controller isn't doing anything odd that causes the USB drives to heat up

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5138]
We've seen USB drives plugged into VxComputer get hotter than we'd expect (hotter than surrounding metals), even when nothing is actively being written to them (as far as we can tell) and even outside of our app, e.g., during imaging. Let's see if there's a lower-level explanation here.

https://votingworks.slack.com/archives/C062Y0ZFKFT/p1722030480093689

**Comment by amcmanus** [comment]
There does not appear to be any underlying condition/cause within our app related to drives heating up. Multiple models exhibit the same behavior when in-use across different systems (Lenovo, VxComputer, System76, and Mac). When idle or even unmounted, they still heat up over time. We can lessen the impact by choosing drives with a plastic case rather than exposed metal, but physics guarantees usb drives will heat up when connected.

**Comment by arsalansufi** [comment]
Thanks for quickly validating this @amcmanus!
