### ISSUE TITLE
VxAdmin: HW diagnostics page has a spinning icon instead of checkmark for the printer connected status

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5151]
Diagnostics Page has a spinning icon instead of checkmark for the printer status connected

Issue automatically created from Slack feedback reported by caroline: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1721856319773999?thread_ts=1721856319.773999&cid=CJU9MSC6S

**Comment by adghayes** [comment]
I'm not able to reproduce this in dev. I think this is prod-specific, possibly with some permissions issue around making IPP requests to the printer.

The spinning icon is happening because the printer is an IPP printer, so our software is waiting on responses to IPP queries to get rich status like "out of paper" etc. Since those requests are failing, it just keeps spinning.
