### ISSUE TITLE
precinct-scanner: more / faster on-screen feedback

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#518]
Things to make the scanner feel snappier:
- show "your ballot was counted" sooner if possible
- show "overvote" or "blank" warning earlier if possible (as ballot is being rejected, for example.)

**Comment by carolinemodic** [comment]
For rejecting/reviewing a ballot the precinct-scanner UI is NOT currently waiting on the ejection of the ballot forward to show the UI. The time it takes for polling, the network requests necessary etc., just happen to take up about the same amount of time so it feels that way in practice. You can prove this by adding a sleep(5000) at the start of reviewSheet or rejectSheet in https://github.com/votingworks/vxsuite/blob/main/apps/module-scan/src/scanners/plustek.ts

This is because the precinct-scanner fronted is not waiting on the batch to finish scanning, it is just waiting for there to be a sheet marked as needs adjudication which happens in module-scan as soon as the sheet is done being interpreted. 

However, when a ballot is successfully cast the ejecting to the back of the scanner IS currently being waited on. This is because in this case precinct-scanner waits for an endedAt time to be written to the batch by module-scan which only happens when the entire scanning process, including the ejection to the back is complete. This happens rather quickly however, and in practice I don't think there is going to be any noticeable time saved by changing this, but we could potentially shave off about 100ms. I experimented with writing a "scanningCompleteAt" time in addition to the current "endedAt" time as soon as we know the sheet is "castable" in module-scan and the frontend of precinct-scanner (which polls every 100 second) either sees these times appear in the same API call or at most one API call sooner. If I change the polling interval to 10ms then it shows up 2-3 API calls sooner.

**Comment by carolinemodic** [comment]
Draft PR for the successful path: https://github.com/votingworks/vxsuite/pull/741

**Comment by benadida** [comment]
it's fine as is, redesign already makes this better.
