### ISSUE TITLE
Have a simple solution ready for Rochester summing across wards' VxAdmin CSV reports

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5240]
Also double check that on v3.1, the CSV export includes post-adjudicated results

**Comment by mattroe** [comment]
@arsalansufi used the NH test ballot to create a sample set of data that should have all permutations of adjudicated values from admin. I am suggesting we have folks export the full election tally CSV (instead of using the report builder) for this flow for an easy consistent report export process. This won't include every cut, but I don't think that's necessary for this aggregation.

[unofficial-full-election-tally-report__2024-08-19_11-27-20.csv](https://github.com/user-attachments/files/16663998/unofficial-full-election-tally-report__2024-08-19_11-27-20.csv)

**Comment by arsalansufi** [comment]
Current proposed solution: https://votingworks.slack.com/archives/C0745GJJGDR/p1724682909016029

**Comment by arsalansufi** [comment]
Final iteration with usage instructions! https://docs.google.com/document/d/1FCSNW1gYW9fAiOc3eT8Yw1Hw43l9oh6UxnamYkTkAYQ/edit?usp=sharing
