### ISSUE TITLE
VxMark: PAT input shows up as not connected in HW diagnostic even when connected and working

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5275]
VxMark: PAT input shows up as not connected in HW diagnostic even when connected and working

This is very possibly specific to production and the 150s

Issue automatically created from Slack feedback reported by arsalan: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1724078551652199

**Comment by kshen0** [comment]
First, due to complexity of various PAT and diagnostic flows we should note
* the PAT tutorial that a voter sees (when plugging a device in for the first time) is not related to this flow
* there are backend and frontend components for the sys admin hardware diagnostic report ("Readiness Report")

The bug is that the "Connected / Not Connected" text reports on PAT device connection status ie. whether a sip & puff is plugged in. It _should_ report on whether the PAT input and associated business logic works, which is technically:
1. Whether the daemon is running (also implies the daemon can reach the firmware)
2. Whether daemon, backend, and frontend business logic can correctly handle sip/puff signals from the device

**Product decision**

Change diagnostic report copy: change status text from "Connected / Not Connected" to "Available / Not Available"

**Code changes**

* allow status text override in https://github.com/votingworks/vxsuite/blob/main/libs/ui/src/diagnostics/mark_scan_device_diagnostic_section.tsx#L32
* call isAccessibleControllerDaemonRunning from [here](https://github.com/votingworks/vxsuite/blob/65e2910634bc3cab072f4f40cd986432b4dca88c/apps/mark-scan/backend/src/readiness_report.ts#L54) and [here](https://github.com/votingworks/vxsuite/blob/65e2910634bc3cab072f4f40cd986432b4dca88c/apps/mark-scan/frontend/src/pages/diagnostics/diagnostics_screen.tsx#L158)
* on the 155, gracefully fall back to reporting PAT device connection status (current behavior)
  * this is because the 155 PAT daemon is separate from the accessible controller daemon. The 155 PAT daemon doesn't report its PID in the same way the accessible controller daemons do, so the mark-scan app doesn't have a clean way to check that the 155 PAT daemon is running. We don't want to invest in extending the 155 PAT daemon at this moment
