### ISSUE TITLE
bmd: review screen doesn't highlight which contest

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#584]
this may be a regression, reported by @adghayes.

**Comment by carolinemodic** [comment]
I'm pretty sure they are being highlighted but I'm not entirely sure I understand what the bug is, @benadida do we have the original report?

**Comment by benadida** [comment]
@adghayes can you say more about this bug. I think you were using the accessible controller on the review screen?

**Comment by adghayes** [comment]
Attached video with reproduction. **When navigating with the accessibility controller,** candidates are highlighted on each race screen as you navigate, but on the review screen, races are not highlighted when navigating. You can't visually tell which element is in focus, although it is clear the focus is changing based on the audio.

https://zube.io/files/votingworks/e5df683463f2a059c696f3b88cf5f568-img_4666_480p.mov

**Comment by carolinemodic** [comment]
I believe this bug has been fixed since we last cut vxsuite-complete-system. We migrated the buttons in question here to a shared Button component since then so I believe that somehow fixed this bug, and also for some reason made these buttons a darker grey. 
Repro Steps:
Install Clean Ubuntu on Lenovo Thinkpad
Install / Build vxsuite-complete-system
Run BMD and see bug reproduce
Update Vxsuite to most recent code on main and rebuild
Run BMD and see bug no longer reproduce

https://zube.io/files/votingworks/78c71be31108c383d01d2aa6d5bff1b7-img_1409-2.mov
