### ISSUE TITLE
don't print report on vxmark+print when there's a precinct scanner

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#591]
When a precinct has a precinct scanner that prints polls open / close reports, we don't want the BMD with integrated printing to do the same.

This might be a configuration parameter on the BMD with integrated printing. Or it may be done with a prompt in the poll worker screen on the BMD. Or maybe it's part of the election configuration file, indicating which precincts have a precinct scanner. All worth discussing.

**Comment by beausmith** [comment]
@benadida and I chatted through a few scenarios and wanted to present the following draft proposal for feedback from @eventualbuddha and @carolinemodic. (@benadida Please sanity-check this to ensure I did not forget anything.)

Add an Admin setting to define how the ballots printed from this BMD are to be scanned. This setting would be available for appModes: `VxPrint` and `VxMarkPlusVxPrint` because these both collect tallies and could be used with a Precinct Ballot Scanner.

# New BMD Setting: "Ballot Scanning Mode"

This would be a segmented button that toggles between "Precinct Ballot Scanning" and "Central Ballot Scanning".

## Precinct Ballot Scanning (default)
- BMD does not record a tally the ballots printed because the precinct scanner is responsible for precinct tally.
- BMD does keep a count of how many ballots were printed and can print a simple report with this count.
- When poll worker card is inserted and contains a precinct scanner open/close report, a screen is displayed which has:
    - title: Print Precinct Ballot Scanner Open Polls Report
    - content based upon number of reports on poll worker card: 
        - The Open Polls Report will contain data from 1 Precinct Ballot Scanner
        - The Open Polls Report will contain data from 2 Precinct Ballot Scanners
    - button: Print Open Report

## Central Ballot Scanning
- Does keep a tally of the ballots it prints to ensure that the precinct tally matches the central scan tally.

**Comment by benadida** [comment]
@beausmith I'm thinking we should go further and not have a central ballot scanning mode. Meaning we just remove the tally function on BMDs and only print precinct scanner tallies on the poll worker card. The tallies we were producing on BMDs were never entirely correct anyways, because of possible spoiled ballots. I don't see a reason to maintain this feature when we have a better approach with the precinct scanner.
